/**
 * GHL API — associations namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 10 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the associations namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all associations operations
 */
export function createAssociationsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Create Relation for you associated entities.
     * POST /associations/relations
     * @param {object} body — request body
     * @scopes associations/relation.write
     */
    async createRelation(body) {
      return request('POST', '/associations/relations', { body });
    },

    /**
     * Get all relations By record Id
     * GET /associations/relations/{recordId}
     * @param {string} recordId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.skip] (required)
     * @param {*} [query.limit] (required)
     * @param {*} [query.associationIds]
     * @scopes associations/relation.readonly
     */
    async getRelationsByRecordId(recordId, { locationId, skip, limit, associationIds } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (associationIds !== undefined) _params['associationIds'] = associationIds;
      return request('GET', `/associations/relations/${recordId}`, { query: _params });
    },

    /**
     * Delete Relation
     * DELETE /associations/relations/{relationId}
     * @param {string} relationId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes associations/relation.write
     */
    async deleteRelation(relationId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('DELETE', `/associations/relations/${relationId}`, { query: _params });
    },

    /**
     * Get association key by key name
     * GET /associations/key/{key_name}
     * @param {string} key_name
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes associations.readonly
     */
    async getAssociationKeyByKeyName(key_name, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/associations/key/${key_name}`, { query: _params });
    },

    /**
     * Get association by object keys
     * GET /associations/objectKey/{objectKey}
     * @param {string} objectKey
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @scopes associations.readonly
     */
    async getAssociationByObjectKeys(objectKey, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/associations/objectKey/${objectKey}`, { query: _params });
    },

    /**
     * Get association by ID
     * GET /associations/{associationId}
     * @param {string} associationId
     * @scopes associations.readonly
     */
    async getAssociationByID(associationId) {
      return request('GET', `/associations/${associationId}`);
    },

    /**
     * Update Association By Id
     * PUT /associations/{associationId}
     * @param {string} associationId
     * @param {object} body — request body
     * @scopes associations.write
     */
    async updateAssociation(associationId, body) {
      return request('PUT', `/associations/${associationId}`, { body });
    },

    /**
     * Delete Association
     * DELETE /associations/{associationId}
     * @param {string} associationId
     * @scopes associations.write
     */
    async deleteAssociation(associationId) {
      return request('DELETE', `/associations/${associationId}`);
    },

    /**
     * Get all associations for a sub-account / location
     * GET /associations/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.skip] (required)
     * @param {*} [query.limit] (required)
     * @scopes associations.readonly
     */
    async findAssociations({ locationId, skip, limit } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      return request('GET', '/associations/', { query: _params });
    },

    /**
     * Create Association
     * POST /associations/
     * @param {object} body — request body
     * @scopes associations.write
     */
    async createAssociation(body) {
      return request('POST', '/associations/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  createRelation: ["associations/relation.write"],
  getRelationsByRecordId: ["associations/relation.readonly"],
  deleteRelation: ["associations/relation.write"],
  getAssociationKeyByKeyName: ["associations.readonly"],
  getAssociationByObjectKeys: ["associations.readonly"],
  getAssociationByID: ["associations.readonly"],
  updateAssociation: ["associations.write"],
  deleteAssociation: ["associations.write"],
  findAssociations: ["associations.readonly"],
  createAssociation: ["associations.write"],
};
