/**
 * GHL API — blogs namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 7 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the blogs namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all blogs operations
 */
export function createBlogsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Check url slug
     * GET /blogs/posts/url-slug-exists
     * @param {object} [query]
     * @param {*} [query.urlSlug] (required)
     * @param {*} [query.locationId] (required)
     * @param {*} [query.postId]
     * @scopes blogs/check-slug.readonly
     */
    async checkUrlSlugExists({ urlSlug, locationId, postId } = {}) {
      const _params = {};
      if (urlSlug !== undefined) _params['urlSlug'] = urlSlug;
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (postId !== undefined) _params['postId'] = postId;
      return request('GET', '/blogs/posts/url-slug-exists', { query: _params });
    },

    /**
     * Update Blog Post
     * PUT /blogs/posts/{postId}
     * @param {string} postId
     * @param {object} body — request body
     * @scopes blogs/post-update.write
     */
    async updateBlogPost(postId, body) {
      return request('PUT', `/blogs/posts/${postId}`, { body });
    },

    /**
     * Create Blog Post
     * POST /blogs/posts
     * @param {object} body — request body
     * @scopes blogs/post.write
     */
    async createBlogPost(body) {
      return request('POST', '/blogs/posts', { body });
    },

    /**
     * Get all authors
     * GET /blogs/authors
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @scopes blogs/author.readonly
     */
    async getAllBlogAuthorsByLocation({ locationId, limit, offset } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/blogs/authors', { query: _params });
    },

    /**
     * Get all categories
     * GET /blogs/categories
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @scopes blogs/category.readonly
     */
    async getAllCategoriesByLocation({ locationId, limit, offset } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/blogs/categories', { query: _params });
    },

    /**
     * Get Blog posts by Blog ID
     * GET /blogs/posts/all
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.blogId] (required)
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @param {*} [query.searchTerm]
     * @param {*} [query.status]
     * @scopes blogs/posts.readonly
     */
    async getBlogPost({ locationId, blogId, limit, offset, searchTerm, status } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (blogId !== undefined) _params['blogId'] = blogId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (searchTerm !== undefined) _params['searchTerm'] = searchTerm;
      if (status !== undefined) _params['status'] = status;
      return request('GET', '/blogs/posts/all', { query: _params });
    },

    /**
     * Get Blogs by Location ID
     * GET /blogs/site/all
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.skip] (required)
     * @param {*} [query.limit] (required)
     * @param {*} [query.searchTerm]
     * @scopes blogs/list.readonly
     */
    async getBlogs({ locationId, skip, limit, searchTerm } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (searchTerm !== undefined) _params['searchTerm'] = searchTerm;
      return request('GET', '/blogs/site/all', { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  checkUrlSlugExists: ["blogs/check-slug.readonly"],
  updateBlogPost: ["blogs/post-update.write"],
  createBlogPost: ["blogs/post.write"],
  getAllBlogAuthorsByLocation: ["blogs/author.readonly"],
  getAllCategoriesByLocation: ["blogs/category.readonly"],
  getBlogPost: ["blogs/posts.readonly"],
  getBlogs: ["blogs/list.readonly"],
};
