/**
 * GHL API — businesses namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 5 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the businesses namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all businesses operations
 */
export function createBusinessesNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Business
     * GET /businesses/{businessId}
     * @param {string} businessId
     * @scopes businesses.readonly
     */
    async getBusiness(businessId) {
      return request('GET', `/businesses/${businessId}`);
    },

    /**
     * Update Business
     * PUT /businesses/{businessId}
     * @param {string} businessId
     * @param {object} body — request body
     * @scopes businesses.write
     */
    async updateBusiness(businessId, body) {
      return request('PUT', `/businesses/${businessId}`, { body });
    },

    /**
     * Delete Business
     * DELETE /businesses/{businessId}
     * @param {string} businessId
     * @scopes businesses.write
     */
    async deleteBusiness(businessId) {
      return request('DELETE', `/businesses/${businessId}`);
    },

    /**
     * Get Businesses by Location
     * GET /businesses/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes businesses.readonly
     */
    async getBusinessesByLocation({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/businesses/', { query: _params });
    },

    /**
     * Create Business
     * POST /businesses/
     * @param {object} body — request body
     * @scopes businesses.write
     */
    async createBusiness(body) {
      return request('POST', '/businesses/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getBusiness: ["businesses.readonly"],
  updateBusiness: ["businesses.write"],
  deleteBusiness: ["businesses.write"],
  getBusinessesByLocation: ["businesses.readonly"],
  createBusiness: ["businesses.write"],
};
