/**
 * GHL API — calendars namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 34 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the calendars namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all calendars operations
 */
export function createCalendarsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Groups
     * GET /calendars/groups
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes calendars/groups.readonly
     */
    async getGroups({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/calendars/groups', { query: _params });
    },

    /**
     * Create Calendar Group
     * POST /calendars/groups
     * @param {object} body — request body
     * @scopes calendars/groups.write
     */
    async createCalendarGroup(body) {
      return request('POST', '/calendars/groups', { body });
    },

    /**
     * Validate group slug
     * POST /calendars/groups/validate-slug
     * @param {object} body — request body
     * @scopes calendars/groups.write
     */
    async validateGroupsSlug(body) {
      return request('POST', '/calendars/groups/validate-slug', { body });
    },

    /**
     * Update Group
     * PUT /calendars/groups/{groupId}
     * @param {string} groupId
     * @param {object} body — request body
     * @scopes calendars/groups.write
     */
    async editGroup(groupId, body) {
      return request('PUT', `/calendars/groups/${groupId}`, { body });
    },

    /**
     * Delete Group
     * DELETE /calendars/groups/{groupId}
     * @param {string} groupId
     * @scopes calendars/groups.write
     */
    async deleteGroup(groupId) {
      return request('DELETE', `/calendars/groups/${groupId}`);
    },

    /**
     * Disable Group
     * PUT /calendars/groups/{groupId}/status
     * @param {string} groupId
     * @param {object} body — request body
     * @scopes calendars/groups.write
     */
    async disableGroup(groupId, body) {
      return request('PUT', `/calendars/groups/${groupId}/status`, { body });
    },

    /**
     * Create appointment
     * POST /calendars/events/appointments
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async createAppointment(body) {
      return request('POST', '/calendars/events/appointments', { body });
    },

    /**
     * Get Appointment
     * GET /calendars/events/appointments/{eventId}
     * @param {string} eventId
     * @scopes calendars/events.readonly
     */
    async getAppointment(eventId) {
      return request('GET', `/calendars/events/appointments/${eventId}`);
    },

    /**
     * Update Appointment
     * PUT /calendars/events/appointments/{eventId}
     * @param {string} eventId
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async editAppointment(eventId, body) {
      return request('PUT', `/calendars/events/appointments/${eventId}`, { body });
    },

    /**
     * Get Calendar Events
     * GET /calendars/events
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.userId]
     * @param {*} [query.calendarId]
     * @param {*} [query.groupId]
     * @param {*} [query.startTime] (required)
     * @param {*} [query.endTime] (required)
     * @scopes calendars/events.readonly
     */
    async getCalendarEvents({ locationId, userId, calendarId, groupId, startTime, endTime } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (userId !== undefined) _params['userId'] = userId;
      if (calendarId !== undefined) _params['calendarId'] = calendarId;
      if (groupId !== undefined) _params['groupId'] = groupId;
      if (startTime !== undefined) _params['startTime'] = startTime;
      if (endTime !== undefined) _params['endTime'] = endTime;
      return request('GET', '/calendars/events', { query: _params });
    },

    /**
     * Get Blocked Slots
     * GET /calendars/blocked-slots
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.userId]
     * @param {*} [query.calendarId]
     * @param {*} [query.groupId]
     * @param {*} [query.startTime] (required)
     * @param {*} [query.endTime] (required)
     * @scopes calendars/events.readonly
     */
    async getBlockedSlots({ locationId, userId, calendarId, groupId, startTime, endTime } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (userId !== undefined) _params['userId'] = userId;
      if (calendarId !== undefined) _params['calendarId'] = calendarId;
      if (groupId !== undefined) _params['groupId'] = groupId;
      if (startTime !== undefined) _params['startTime'] = startTime;
      if (endTime !== undefined) _params['endTime'] = endTime;
      return request('GET', '/calendars/blocked-slots', { query: _params });
    },

    /**
     * Create Block Slot
     * POST /calendars/events/block-slots
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async createBlockSlot(body) {
      return request('POST', '/calendars/events/block-slots', { body });
    },

    /**
     * Update Block Slot
     * PUT /calendars/events/block-slots/{eventId}
     * @param {string} eventId
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async editBlockSlot(eventId, body) {
      return request('PUT', `/calendars/events/block-slots/${eventId}`, { body });
    },

    /**
     * Get Free Slots
     * GET /calendars/{calendarId}/free-slots
     * @param {string} calendarId
     * @param {object} [query]
     * @param {*} [query.startDate] (required)
     * @param {*} [query.endDate] (required)
     * @param {*} [query.timezone]
     * @param {*} [query.userId]
     * @param {*} [query.userIds]
     * @scopes calendars.readonly
     */
    async getSlots(calendarId, { startDate, endDate, timezone, userId, userIds } = {}) {
      const _params = {};
      if (startDate !== undefined) _params['startDate'] = startDate;
      if (endDate !== undefined) _params['endDate'] = endDate;
      if (timezone !== undefined) _params['timezone'] = timezone;
      if (userId !== undefined) _params['userId'] = userId;
      if (userIds !== undefined) _params['userIds'] = userIds;
      return request('GET', `/calendars/${calendarId}/free-slots`, { query: _params });
    },

    /**
     * Get Calendar
     * GET /calendars/{calendarId}
     * @param {string} calendarId
     * @scopes calendars.readonly
     */
    async getCalendar(calendarId) {
      return request('GET', `/calendars/${calendarId}`);
    },

    /**
     * Update Calendar
     * PUT /calendars/{calendarId}
     * @param {string} calendarId
     * @param {object} body — request body
     * @scopes calendars.write
     */
    async updateCalendar(calendarId, body) {
      return request('PUT', `/calendars/${calendarId}`, { body });
    },

    /**
     * Delete Calendar
     * DELETE /calendars/{calendarId}
     * @param {string} calendarId
     * @scopes calendars.write
     */
    async deleteCalendar(calendarId) {
      return request('DELETE', `/calendars/${calendarId}`);
    },

    /**
     * Delete Event
     * DELETE /calendars/events/{eventId}
     * @param {string} eventId
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async deleteEvent(eventId, body) {
      return request('DELETE', `/calendars/events/${eventId}`, { body });
    },

    /**
     * Get Notes
     * GET /calendars/appointments/{appointmentId}/notes
     * @param {string} appointmentId
     * @param {object} [query]
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @scopes calendars/events.readonly
     */
    async getAppointmentNotes(appointmentId, { limit, offset } = {}) {
      const _params = {};
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', `/calendars/appointments/${appointmentId}/notes`, { query: _params });
    },

    /**
     * Create Note
     * POST /calendars/appointments/{appointmentId}/notes
     * @param {string} appointmentId
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async createAppointmentNote(appointmentId, body) {
      return request('POST', `/calendars/appointments/${appointmentId}/notes`, { body });
    },

    /**
     * Update Note
     * PUT /calendars/appointments/{appointmentId}/notes/{noteId}
     * @param {string} appointmentId
     * @param {string} noteId
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async updateAppointmentNote(appointmentId, noteId, body) {
      return request('PUT', `/calendars/appointments/${appointmentId}/notes/${noteId}`, { body });
    },

    /**
     * Delete Note
     * DELETE /calendars/appointments/{appointmentId}/notes/{noteId}
     * @param {string} appointmentId
     * @param {string} noteId
     * @scopes calendars/events.write
     */
    async deleteAppointmentNote(appointmentId, noteId) {
      return request('DELETE', `/calendars/appointments/${appointmentId}/notes/${noteId}`);
    },

    /**
     * Get Calendar Resource
     * GET /calendars/resources/{resourceType}/{id}
     * @param {string} resourceType
     * @param {string} id
     * @scopes calendars/resources.readonly
     */
    async getCalendarResource(resourceType, id) {
      return request('GET', `/calendars/resources/${resourceType}/${id}`);
    },

    /**
     * Update Calendar Resource
     * PUT /calendars/resources/{resourceType}/{id}
     * @param {string} resourceType
     * @param {string} id
     * @param {object} body — request body
     * @scopes calendars/resources.write
     */
    async updateCalendarResource(resourceType, id, body) {
      return request('PUT', `/calendars/resources/${resourceType}/${id}`, { body });
    },

    /**
     * Delete Calendar Resource
     * DELETE /calendars/resources/{resourceType}/{id}
     * @param {string} resourceType
     * @param {string} id
     * @scopes calendars/resources.write
     */
    async deleteCalendarResource(resourceType, id) {
      return request('DELETE', `/calendars/resources/${resourceType}/${id}`);
    },

    /**
     * List Calendar Resources
     * GET /calendars/resources/{resourceType}
     * @param {string} resourceType
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.limit] (required)
     * @param {*} [query.skip] (required)
     * @scopes calendars/resources.readonly
     */
    async fetchCalendarResources(resourceType, { locationId, limit, skip } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (limit !== undefined) _params['limit'] = limit;
      if (skip !== undefined) _params['skip'] = skip;
      return request('GET', `/calendars/resources/${resourceType}`, { query: _params });
    },

    /**
     * Create Calendar Resource
     * POST /calendars/resources/{resourceType}
     * @param {string} resourceType
     * @param {object} body — request body
     * @scopes calendars/resources.write
     */
    async createCalendarResource(resourceType, body) {
      return request('POST', `/calendars/resources/${resourceType}`, { body });
    },

    /**
     * Get notifications
     * GET /calendars/{calendarId}/notifications
     * @param {string} calendarId
     * @param {object} [query]
     * @param {*} [query.isActive]
     * @param {*} [query.deleted]
     * @param {*} [query.limit]
     * @param {*} [query.skip]
     * @scopes calendars/events.readonly
     */
    async getEventNotification(calendarId, { isActive, deleted, limit, skip } = {}) {
      const _params = {};
      if (isActive !== undefined) _params['isActive'] = isActive;
      if (deleted !== undefined) _params['deleted'] = deleted;
      if (limit !== undefined) _params['limit'] = limit;
      if (skip !== undefined) _params['skip'] = skip;
      return request('GET', `/calendars/${calendarId}/notifications`, { query: _params });
    },

    /**
     * Create notification
     * POST /calendars/{calendarId}/notifications
     * @param {string} calendarId
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async createEventNotification(calendarId, body) {
      return request('POST', `/calendars/${calendarId}/notifications`, { body });
    },

    /**
     * Get notification
     * GET /calendars/{calendarId}/notifications/{notificationId}
     * @param {string} calendarId
     * @param {string} notificationId
     * @scopes calendars/events.readonly
     */
    async findEventNotification(calendarId, notificationId) {
      return request('GET', `/calendars/${calendarId}/notifications/${notificationId}`);
    },

    /**
     * Update notification
     * PUT /calendars/{calendarId}/notifications/{notificationId}
     * @param {string} calendarId
     * @param {string} notificationId
     * @param {object} body — request body
     * @scopes calendars/events.write
     */
    async updateEventNotification(calendarId, notificationId, body) {
      return request('PUT', `/calendars/${calendarId}/notifications/${notificationId}`, { body });
    },

    /**
     * Delete Notification
     * DELETE /calendars/{calendarId}/notifications/{notificationId}
     * @param {string} calendarId
     * @param {string} notificationId
     * @scopes calendars/events.write
     */
    async deleteEventNotification(calendarId, notificationId) {
      return request('DELETE', `/calendars/${calendarId}/notifications/${notificationId}`);
    },

    /**
     * Get Calendars
     * GET /calendars/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.groupId]
     * @param {*} [query.showDrafted]
     * @scopes calendars.readonly
     */
    async getCalendars({ locationId, groupId, showDrafted } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (groupId !== undefined) _params['groupId'] = groupId;
      if (showDrafted !== undefined) _params['showDrafted'] = showDrafted;
      return request('GET', '/calendars/', { query: _params });
    },

    /**
     * Create Calendar
     * POST /calendars/
     * @param {object} body — request body
     * @scopes calendars.write
     */
    async createCalendar(body) {
      return request('POST', '/calendars/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getGroups: ["calendars/groups.readonly"],
  createCalendarGroup: ["calendars/groups.write"],
  validateGroupsSlug: ["calendars/groups.write"],
  editGroup: ["calendars/groups.write"],
  deleteGroup: ["calendars/groups.write"],
  disableGroup: ["calendars/groups.write"],
  createAppointment: ["calendars/events.write"],
  getAppointment: ["calendars/events.readonly"],
  editAppointment: ["calendars/events.write"],
  getCalendarEvents: ["calendars/events.readonly"],
  getBlockedSlots: ["calendars/events.readonly"],
  createBlockSlot: ["calendars/events.write"],
  editBlockSlot: ["calendars/events.write"],
  getSlots: ["calendars.readonly"],
  getCalendar: ["calendars.readonly"],
  updateCalendar: ["calendars.write"],
  deleteCalendar: ["calendars.write"],
  deleteEvent: ["calendars/events.write"],
  getAppointmentNotes: ["calendars/events.readonly"],
  createAppointmentNote: ["calendars/events.write"],
  updateAppointmentNote: ["calendars/events.write"],
  deleteAppointmentNote: ["calendars/events.write"],
  getCalendarResource: ["calendars/resources.readonly"],
  updateCalendarResource: ["calendars/resources.write"],
  deleteCalendarResource: ["calendars/resources.write"],
  fetchCalendarResources: ["calendars/resources.readonly"],
  createCalendarResource: ["calendars/resources.write"],
  getEventNotification: ["calendars/events.readonly"],
  createEventNotification: ["calendars/events.write"],
  findEventNotification: ["calendars/events.readonly"],
  updateEventNotification: ["calendars/events.write"],
  deleteEventNotification: ["calendars/events.write"],
  getCalendars: ["calendars.readonly"],
  createCalendar: ["calendars.write"],
};
