/**
 * GHL API — campaigns namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 1 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the campaigns namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all campaigns operations
 */
export function createCampaignsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Campaigns
     * GET /campaigns/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.status]
     * @scopes campaigns.readonly
     */
    async getCampaigns({ locationId, status } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (status !== undefined) _params['status'] = status;
      return request('GET', '/campaigns/', { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getCampaigns: ["campaigns.readonly"],
};
