/**
 * GHL API — companies namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 1 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the companies namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all companies operations
 */
export function createCompaniesNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Company
     * GET /companies/{companyId}
     * @param {string} companyId
     * @scopes companies.readonly
     */
    async getCompany(companyId) {
      return request('GET', `/companies/${companyId}`);
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getCompany: ["companies.readonly"],
};
