/**
 * GHL API — contacts namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 32 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the contacts namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all contacts operations
 */
export function createContactsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Search Contacts
     * POST /contacts/search
     * @param {object} body — request body
     * @scopes contacts.readonly
     */
    async searchContactsAdvanced(body) {
      return request('POST', '/contacts/search', { body });
    },

    /**
     * Get Duplicate Contact
     * GET /contacts/search/duplicate
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.number]
     * @param {*} [query.email]
     * @scopes contacts.readonly
     */
    async getDuplicateContact({ locationId, number, email } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (number !== undefined) _params['number'] = number;
      if (email !== undefined) _params['email'] = email;
      return request('GET', '/contacts/search/duplicate', { query: _params });
    },

    /**
     * Get all Tasks
     * GET /contacts/{contactId}/tasks
     * @param {string} contactId
     * @scopes contacts.readonly
     */
    async getAllTasks(contactId) {
      return request('GET', `/contacts/${contactId}/tasks`);
    },

    /**
     * Create Task
     * POST /contacts/{contactId}/tasks
     * @param {string} contactId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async createTask(contactId, body) {
      return request('POST', `/contacts/${contactId}/tasks`, { body });
    },

    /**
     * Get Task
     * GET /contacts/{contactId}/tasks/{taskId}
     * @param {string} contactId
     * @param {string} taskId
     * @scopes contacts.readonly
     */
    async getTask(contactId, taskId) {
      return request('GET', `/contacts/${contactId}/tasks/${taskId}`);
    },

    /**
     * Update Task
     * PUT /contacts/{contactId}/tasks/{taskId}
     * @param {string} contactId
     * @param {string} taskId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async updateTask(contactId, taskId, body) {
      return request('PUT', `/contacts/${contactId}/tasks/${taskId}`, { body });
    },

    /**
     * Delete Task
     * DELETE /contacts/{contactId}/tasks/{taskId}
     * @param {string} contactId
     * @param {string} taskId
     * @scopes contacts.write
     */
    async deleteTask(contactId, taskId) {
      return request('DELETE', `/contacts/${contactId}/tasks/${taskId}`);
    },

    /**
     * Update Task Completed
     * PUT /contacts/{contactId}/tasks/{taskId}/completed
     * @param {string} contactId
     * @param {string} taskId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async updateTaskCompleted(contactId, taskId, body) {
      return request('PUT', `/contacts/${contactId}/tasks/${taskId}/completed`, { body });
    },

    /**
     * Get Appointments for Contact
     * GET /contacts/{contactId}/appointments
     * @param {string} contactId
     * @scopes contacts.readonly
     */
    async getAppointmentsForContact(contactId) {
      return request('GET', `/contacts/${contactId}/appointments`);
    },

    /**
     * Add Tags
     * POST /contacts/{contactId}/tags
     * @param {string} contactId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async addTags(contactId, body) {
      return request('POST', `/contacts/${contactId}/tags`, { body });
    },

    /**
     * Remove Tags
     * DELETE /contacts/{contactId}/tags
     * @param {string} contactId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async removeTags(contactId, body) {
      return request('DELETE', `/contacts/${contactId}/tags`, { body });
    },

    /**
     * Get All Notes
     * GET /contacts/{contactId}/notes
     * @param {string} contactId
     * @scopes contacts.readonly
     */
    async getAllNotes(contactId) {
      return request('GET', `/contacts/${contactId}/notes`);
    },

    /**
     * Create Note
     * POST /contacts/{contactId}/notes
     * @param {string} contactId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async createNote(contactId, body) {
      return request('POST', `/contacts/${contactId}/notes`, { body });
    },

    /**
     * Get Note
     * GET /contacts/{contactId}/notes/{id}
     * @param {string} contactId
     * @param {string} id
     * @scopes contacts.readonly
     */
    async getNote(contactId, id) {
      return request('GET', `/contacts/${contactId}/notes/${id}`);
    },

    /**
     * Update Note
     * PUT /contacts/{contactId}/notes/{id}
     * @param {string} contactId
     * @param {string} id
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async updateNote(contactId, id, body) {
      return request('PUT', `/contacts/${contactId}/notes/${id}`, { body });
    },

    /**
     * Delete Note
     * DELETE /contacts/{contactId}/notes/{id}
     * @param {string} contactId
     * @param {string} id
     * @scopes contacts.write
     */
    async deleteNote(contactId, id) {
      return request('DELETE', `/contacts/${contactId}/notes/${id}`);
    },

    /**
     * Update Contacts Tags
     * POST /contacts/bulk/tags/update/{type}
     * @param {string} type
     * @param {object} body — request body
     */
    async createAssociation(type, body) {
      return request('POST', `/contacts/bulk/tags/update/${type}`, { body });
    },

    /**
     * Add/Remove Contacts From Business
     * POST /contacts/bulk/business
     * @param {object} body — request body
     */
    async addRemoveContactFromBusiness(body) {
      return request('POST', '/contacts/bulk/business', { body });
    },

    /**
     * Get Contact
     * GET /contacts/{contactId}
     * @param {string} contactId
     * @scopes contacts.readonly
     */
    async getContact(contactId) {
      return request('GET', `/contacts/${contactId}`);
    },

    /**
     * Update Contact
     * PUT /contacts/{contactId}
     * @param {string} contactId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async updateContact(contactId, body) {
      return request('PUT', `/contacts/${contactId}`, { body });
    },

    /**
     * Delete Contact
     * DELETE /contacts/{contactId}
     * @param {string} contactId
     * @scopes contacts.write
     */
    async deleteContact(contactId) {
      return request('DELETE', `/contacts/${contactId}`);
    },

    /**
     * Upsert Contact
     * POST /contacts/upsert
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async upsertContact(body) {
      return request('POST', '/contacts/upsert', { body });
    },

    /**
     * Get Contacts By BusinessId
     * GET /contacts/business/{businessId}
     * @param {string} businessId
     * @param {object} [query]
     * @param {*} [query.limit]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.skip]
     * @param {*} [query.query]
     * @scopes contacts.readonly
     */
    async getContactsByBusinessId(businessId, { limit, locationId, skip, query } = {}) {
      const _params = {};
      if (limit !== undefined) _params['limit'] = limit;
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (skip !== undefined) _params['skip'] = skip;
      if (query !== undefined) _params['query'] = query;
      return request('GET', `/contacts/business/${businessId}`, { query: _params });
    },

    /**
     * Add Followers
     * POST /contacts/{contactId}/followers
     * @param {string} contactId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async addFollowersContact(contactId, body) {
      return request('POST', `/contacts/${contactId}/followers`, { body });
    },

    /**
     * Remove Followers
     * DELETE /contacts/{contactId}/followers
     * @param {string} contactId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async removeFollowersContact(contactId, body) {
      return request('DELETE', `/contacts/${contactId}/followers`, { body });
    },

    /**
     * Add Contact to Campaign
     * POST /contacts/{contactId}/campaigns/{campaignId}
     * @param {string} contactId
     * @param {string} campaignId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async addContactToCampaign(contactId, campaignId, body) {
      return request('POST', `/contacts/${contactId}/campaigns/${campaignId}`, { body });
    },

    /**
     * Remove Contact From Campaign
     * DELETE /contacts/{contactId}/campaigns/{campaignId}
     * @param {string} contactId
     * @param {string} campaignId
     * @scopes contacts.write
     */
    async removeContactFromCampaign(contactId, campaignId) {
      return request('DELETE', `/contacts/${contactId}/campaigns/${campaignId}`);
    },

    /**
     * Remove Contact From Every Campaign
     * DELETE /contacts/{contactId}/campaigns/removeAll
     * @param {string} contactId
     * @scopes contacts.write
     */
    async removeContactFromEveryCampaign(contactId) {
      return request('DELETE', `/contacts/${contactId}/campaigns/removeAll`);
    },

    /**
     * Add Contact to Workflow
     * POST /contacts/{contactId}/workflow/{workflowId}
     * @param {string} contactId
     * @param {string} workflowId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async addContactToWorkflow(contactId, workflowId, body) {
      return request('POST', `/contacts/${contactId}/workflow/${workflowId}`, { body });
    },

    /**
     * Delete Contact from Workflow
     * DELETE /contacts/{contactId}/workflow/{workflowId}
     * @param {string} contactId
     * @param {string} workflowId
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async deleteContactFromWorkflow(contactId, workflowId, body) {
      return request('DELETE', `/contacts/${contactId}/workflow/${workflowId}`, { body });
    },

    /**
     * Get Contacts
     * GET /contacts/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.startAfterId]
     * @param {*} [query.startAfter]
     * @param {*} [query.query]
     * @param {*} [query.limit]
     * @scopes contacts.readonly
     */
    async getContacts({ locationId, startAfterId, startAfter, query, limit } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (startAfterId !== undefined) _params['startAfterId'] = startAfterId;
      if (startAfter !== undefined) _params['startAfter'] = startAfter;
      if (query !== undefined) _params['query'] = query;
      if (limit !== undefined) _params['limit'] = limit;
      return request('GET', '/contacts/', { query: _params });
    },

    /**
     * Create Contact
     * POST /contacts/
     * @param {object} body — request body
     * @scopes contacts.write
     */
    async createContact(body) {
      return request('POST', '/contacts/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  searchContactsAdvanced: ["contacts.readonly"],
  getDuplicateContact: ["contacts.readonly"],
  getAllTasks: ["contacts.readonly"],
  createTask: ["contacts.write"],
  getTask: ["contacts.readonly"],
  updateTask: ["contacts.write"],
  deleteTask: ["contacts.write"],
  updateTaskCompleted: ["contacts.write"],
  getAppointmentsForContact: ["contacts.readonly"],
  addTags: ["contacts.write"],
  removeTags: ["contacts.write"],
  getAllNotes: ["contacts.readonly"],
  createNote: ["contacts.write"],
  getNote: ["contacts.readonly"],
  updateNote: ["contacts.write"],
  deleteNote: ["contacts.write"],
  getContact: ["contacts.readonly"],
  updateContact: ["contacts.write"],
  deleteContact: ["contacts.write"],
  upsertContact: ["contacts.write"],
  getContactsByBusinessId: ["contacts.readonly"],
  addFollowersContact: ["contacts.write"],
  removeFollowersContact: ["contacts.write"],
  addContactToCampaign: ["contacts.write"],
  removeContactFromCampaign: ["contacts.write"],
  removeContactFromEveryCampaign: ["contacts.write"],
  addContactToWorkflow: ["contacts.write"],
  deleteContactFromWorkflow: ["contacts.write"],
  getContacts: ["contacts.readonly"],
  createContact: ["contacts.write"],
};
