/**
 * GHL API — conversations namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 19 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the conversations namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all conversations operations
 */
export function createConversationsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Search Conversations
     * GET /conversations/search
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.contactId]
     * @param {*} [query.assignedTo]
     * @param {*} [query.followers]
     * @param {*} [query.mentions]
     * @param {*} [query.query]
     * @param {*} [query.sort]
     * @param {*} [query.startAfterDate]
     * @param {*} [query.id]
     * @param {*} [query.limit]
     * @param {*} [query.lastMessageType]
     * @param {*} [query.lastMessageAction]
     * @param {*} [query.lastMessageDirection]
     * @param {*} [query.status]
     * @param {*} [query.sortBy]
     * @param {*} [query.sortScoreProfile]
     * @param {*} [query.scoreProfile]
     * @param {*} [query.scoreProfileMin]
     * @param {*} [query.scoreProfileMax]
     * @scopes conversations.readonly
     */
    async searchConversation({ locationId, contactId, assignedTo, followers, mentions, query, sort, startAfterDate, id, limit, lastMessageType, lastMessageAction, lastMessageDirection, status, sortBy, sortScoreProfile, scoreProfile, scoreProfileMin, scoreProfileMax } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (assignedTo !== undefined) _params['assignedTo'] = assignedTo;
      if (followers !== undefined) _params['followers'] = followers;
      if (mentions !== undefined) _params['mentions'] = mentions;
      if (query !== undefined) _params['query'] = query;
      if (sort !== undefined) _params['sort'] = sort;
      if (startAfterDate !== undefined) _params['startAfterDate'] = startAfterDate;
      if (id !== undefined) _params['id'] = id;
      if (limit !== undefined) _params['limit'] = limit;
      if (lastMessageType !== undefined) _params['lastMessageType'] = lastMessageType;
      if (lastMessageAction !== undefined) _params['lastMessageAction'] = lastMessageAction;
      if (lastMessageDirection !== undefined) _params['lastMessageDirection'] = lastMessageDirection;
      if (status !== undefined) _params['status'] = status;
      if (sortBy !== undefined) _params['sortBy'] = sortBy;
      if (sortScoreProfile !== undefined) _params['sortScoreProfile'] = sortScoreProfile;
      if (scoreProfile !== undefined) _params['scoreProfile'] = scoreProfile;
      if (scoreProfileMin !== undefined) _params['scoreProfileMin'] = scoreProfileMin;
      if (scoreProfileMax !== undefined) _params['scoreProfileMax'] = scoreProfileMax;
      return request('GET', '/conversations/search', { query: _params });
    },

    /**
     * Get Conversation
     * GET /conversations/{conversationId}
     * @param {string} conversationId
     * @scopes conversations.readonly
     */
    async getConversation(conversationId) {
      return request('GET', `/conversations/${conversationId}`);
    },

    /**
     * Update Conversation
     * PUT /conversations/{conversationId}
     * @param {string} conversationId
     * @param {object} body — request body
     * @scopes conversations.write
     */
    async updateConversation(conversationId, body) {
      return request('PUT', `/conversations/${conversationId}`, { body });
    },

    /**
     * Delete Conversation
     * DELETE /conversations/{conversationId}
     * @param {string} conversationId
     * @scopes conversations.write
     */
    async deleteConversation(conversationId) {
      return request('DELETE', `/conversations/${conversationId}`);
    },

    /**
     * Get email by Id
     * GET /conversations/messages/email/{id}
     * @param {string} id
     */
    async getEmailById(id) {
      return request('GET', `/conversations/messages/email/${id}`);
    },

    /**
     * Cancel a scheduled email message.
     * DELETE /conversations/messages/email/{emailMessageId}/schedule
     * @param {string} emailMessageId
     */
    async cancelScheduledEmailMessage(emailMessageId) {
      return request('DELETE', `/conversations/messages/email/${emailMessageId}/schedule`);
    },

    /**
     * Get message by message id
     * GET /conversations/messages/{id}
     * @param {string} id
     * @scopes conversations/message.readonly
     */
    async getMessage(id) {
      return request('GET', `/conversations/messages/${id}`);
    },

    /**
     * Get messages by conversation id
     * GET /conversations/{conversationId}/messages
     * @param {string} conversationId
     * @param {object} [query]
     * @param {*} [query.lastMessageId]
     * @param {*} [query.limit]
     * @param {*} [query.type]
     * @scopes conversations/message.readonly
     */
    async getMessages(conversationId, { lastMessageId, limit, type } = {}) {
      const _params = {};
      if (lastMessageId !== undefined) _params['lastMessageId'] = lastMessageId;
      if (limit !== undefined) _params['limit'] = limit;
      if (type !== undefined) _params['type'] = type;
      return request('GET', `/conversations/${conversationId}/messages`, { query: _params });
    },

    /**
     * Send a new message
     * POST /conversations/messages
     * @param {object} body — request body
     * @scopes conversations/message.write
     */
    async sendANewMessage(body) {
      return request('POST', '/conversations/messages', { body });
    },

    /**
     * Add an inbound message
     * POST /conversations/messages/inbound
     * @param {object} body — request body
     * @scopes conversations/message.write
     */
    async addAnInboundMessage(body) {
      return request('POST', '/conversations/messages/inbound', { body });
    },

    /**
     * Add an external outbound call
     * POST /conversations/messages/outbound
     * @param {object} body — request body
     * @scopes conversations/message.write
     */
    async addAnOutboundMessage(body) {
      return request('POST', '/conversations/messages/outbound', { body });
    },

    /**
     * Cancel a scheduled message.
     * DELETE /conversations/messages/{messageId}/schedule
     * @param {string} messageId
     * @scopes conversations/message.write
     */
    async cancelScheduledMessage(messageId) {
      return request('DELETE', `/conversations/messages/${messageId}/schedule`);
    },

    /**
     * Upload file attachments
     * POST /conversations/messages/upload
     * @param {object} body — request body
     * @scopes conversations/message.write
     */
    async uploadFileAttachments(body) {
      return request('POST', '/conversations/messages/upload', { body, isMultipart: true });
    },

    /**
     * Update message status
     * PUT /conversations/messages/{messageId}/status
     * @param {string} messageId
     * @param {object} body — request body
     * @scopes conversations/message.write
     */
    async updateMessageStatus(messageId, body) {
      return request('PUT', `/conversations/messages/${messageId}/status`, { body });
    },

    /**
     * Get Recording by Message ID
     * GET /conversations/messages/{messageId}/locations/{locationId}/recording
     * @param {string} locationId
     * @param {string} messageId
     */
    async getMessageRecording(locationId, messageId) {
      return request('GET', `/conversations/messages/${messageId}/locations/${locationId}/recording`);
    },

    /**
     * Get transcription by Message ID
     * GET /conversations/locations/{locationId}/messages/{messageId}/transcription
     * @param {string} locationId
     * @param {string} messageId
     */
    async getMessageTranscription(locationId, messageId) {
      return request('GET', `/conversations/locations/${locationId}/messages/${messageId}/transcription`);
    },

    /**
     * Download transcription by Message ID
     * GET /conversations/locations/{locationId}/messages/{messageId}/transcription/download
     * @param {string} locationId
     * @param {string} messageId
     */
    async downloadMessageTranscription(locationId, messageId) {
      return request('GET', `/conversations/locations/${locationId}/messages/${messageId}/transcription/download`);
    },

    /**
     * Agent/Ai-Bot is typing a message indicator for live chat
     * POST /conversations/providers/live-chat/typing
     * @param {object} body — request body
     * @scopes conversations/livechat.write
     */
    async liveChatAgentTyping(body) {
      return request('POST', '/conversations/providers/live-chat/typing', { body });
    },

    /**
     * Create Conversation
     * POST /conversations/
     * @param {object} body — request body
     * @scopes conversations.write
     */
    async createConversation(body) {
      return request('POST', '/conversations/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  searchConversation: ["conversations.readonly"],
  getConversation: ["conversations.readonly"],
  updateConversation: ["conversations.write"],
  deleteConversation: ["conversations.write"],
  getMessage: ["conversations/message.readonly"],
  getMessages: ["conversations/message.readonly"],
  sendANewMessage: ["conversations/message.write"],
  addAnInboundMessage: ["conversations/message.write"],
  addAnOutboundMessage: ["conversations/message.write"],
  cancelScheduledMessage: ["conversations/message.write"],
  uploadFileAttachments: ["conversations/message.write"],
  updateMessageStatus: ["conversations/message.write"],
  liveChatAgentTyping: ["conversations/livechat.write"],
  createConversation: ["conversations.write"],
};
