/**
 * GHL API — courses namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 1 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the courses namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all courses operations
 */
export function createCoursesNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Import Courses
     * POST /courses/courses-exporter/public/import
     * @param {object} body — request body
     */
    async importCourses(body) {
      return request('POST', '/courses/courses-exporter/public/import', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
};
