/**
 * GHL API — custom-menus namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 5 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the custom-menus namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all custom-menus operations
 */
export function createCustomMenusNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Custom Menu Link
     * GET /custom-menus/{customMenuId}
     * @param {string} customMenuId
     * @scopes custom-menu-link.readonly
     */
    async getCustomMenuById(customMenuId) {
      return request('GET', `/custom-menus/${customMenuId}`);
    },

    /**
     * Update Custom Menu Link
     * PUT /custom-menus/{customMenuId}
     * @param {string} customMenuId
     * @param {object} body — request body
     * @scopes custom-menu-link.write
     */
    async updateCustomMenu(customMenuId, body) {
      return request('PUT', `/custom-menus/${customMenuId}`, { body });
    },

    /**
     * Delete Custom Menu Link
     * DELETE /custom-menus/{customMenuId}
     * @param {string} customMenuId
     * @scopes custom-menu-link.write
     */
    async deleteCustomMenu(customMenuId) {
      return request('DELETE', `/custom-menus/${customMenuId}`);
    },

    /**
     * Get Custom Menu Links
     * GET /custom-menus/
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @param {*} [query.query]
     * @param {*} [query.showOnCompany]
     * @scopes custom-menu-link.readonly
     */
    async getCustomMenus({ locationId, skip, limit, query, showOnCompany } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (query !== undefined) _params['query'] = query;
      if (showOnCompany !== undefined) _params['showOnCompany'] = showOnCompany;
      return request('GET', '/custom-menus/', { query: _params });
    },

    /**
     * Create Custom Menu Link
     * POST /custom-menus/
     * @param {object} body — request body
     * @scopes custom-menu-link.write
     */
    async createCustomMenu(body) {
      return request('POST', '/custom-menus/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getCustomMenuById: ["custom-menu-link.readonly"],
  updateCustomMenu: ["custom-menu-link.write"],
  deleteCustomMenu: ["custom-menu-link.write"],
  getCustomMenus: ["custom-menu-link.readonly"],
  createCustomMenu: ["custom-menu-link.write"],
};
