/**
 * GHL API — custom-fields namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 8 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the custom-fields namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all custom-fields operations
 */
export function createCustomFieldsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Custom Field / Folder By Id
     * GET /custom-fields/{id}
     * @param {string} id
     * @scopes locations/customFields.readonly
     */
    async getCustomFieldById(id) {
      return request('GET', `/custom-fields/${id}`);
    },

    /**
     * Update Custom Field By Id
     * PUT /custom-fields/{id}
     * @param {string} id
     * @param {object} body — request body
     * @scopes locations/customFields.write
     */
    async updateCustomField(id, body) {
      return request('PUT', `/custom-fields/${id}`, { body });
    },

    /**
     * Delete Custom Field By Id
     * DELETE /custom-fields/{id}
     * @param {string} id
     * @scopes locations/customFields.write
     */
    async deleteCustomField(id) {
      return request('DELETE', `/custom-fields/${id}`);
    },

    /**
     * Get Custom Fields By Object Key
     * GET /custom-fields/object-key/{objectKey}
     * @param {string} objectKey
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes locations/customFields.readonly
     */
    async getCustomFieldsByObjectKey(objectKey, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/custom-fields/object-key/${objectKey}`, { query: _params });
    },

    /**
     * Create Custom Field Folder
     * POST /custom-fields/folder
     * @param {object} body — request body
     * @scopes locations/customFields.write
     */
    async createCustomFieldFolder(body) {
      return request('POST', '/custom-fields/folder', { body });
    },

    /**
     * Update Custom Field Folder Name
     * PUT /custom-fields/folder/{id}
     * @param {string} id
     * @param {object} body — request body
     * @scopes locations/customFields.write
     */
    async updateCustomFieldFolder(id, body) {
      return request('PUT', `/custom-fields/folder/${id}`, { body });
    },

    /**
     * Delete Custom Field Folder
     * DELETE /custom-fields/folder/{id}
     * @param {string} id
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes locations/customFields.write
     */
    async deleteCustomFieldFolder(id, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('DELETE', `/custom-fields/folder/${id}`, { query: _params });
    },

    /**
     * Create Custom Field
     * POST /custom-fields/
     * @param {object} body — request body
     * @scopes locations/customFields.write
     */
    async createCustomField(body) {
      return request('POST', '/custom-fields/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getCustomFieldById: ["locations/customFields.readonly"],
  updateCustomField: ["locations/customFields.write"],
  deleteCustomField: ["locations/customFields.write"],
  getCustomFieldsByObjectKey: ["locations/customFields.readonly"],
  createCustomFieldFolder: ["locations/customFields.write"],
  updateCustomFieldFolder: ["locations/customFields.write"],
  deleteCustomFieldFolder: ["locations/customFields.write"],
  createCustomField: ["locations/customFields.write"],
};
