/**
 * GHL API — emails namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 5 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the emails namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all emails operations
 */
export function createEmailsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Campaigns
     * GET /emails/schedule
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.status]
     * @param {*} [query.emailStatus]
     * @param {*} [query.name]
     * @param {*} [query.parentId]
     * @param {*} [query.limitedFields]
     * @param {*} [query.archived]
     * @param {*} [query.campaignsOnly]
     * @param {*} [query.showStats]
     * @scopes emails/schedule.readonly
     */
    async fetchCampaigns({ locationId, limit, offset, status, emailStatus, name, parentId, limitedFields, archived, campaignsOnly, showStats } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (status !== undefined) _params['status'] = status;
      if (emailStatus !== undefined) _params['emailStatus'] = emailStatus;
      if (name !== undefined) _params['name'] = name;
      if (parentId !== undefined) _params['parentId'] = parentId;
      if (limitedFields !== undefined) _params['limitedFields'] = limitedFields;
      if (archived !== undefined) _params['archived'] = archived;
      if (campaignsOnly !== undefined) _params['campaignsOnly'] = campaignsOnly;
      if (showStats !== undefined) _params['showStats'] = showStats;
      return request('GET', '/emails/schedule', { query: _params });
    },

    /**
     * Fetch email templates
     * GET /emails/builder
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.search]
     * @param {*} [query.sortByDate]
     * @param {*} [query.archived]
     * @param {*} [query.builderVersion]
     * @param {*} [query.name]
     * @param {*} [query.parentId]
     * @param {*} [query.originId]
     * @param {*} [query.templatesOnly]
     * @scopes emails/builder.readonly
     */
    async fetchTemplate({ locationId, limit, offset, search, sortByDate, archived, builderVersion, name, parentId, originId, templatesOnly } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (search !== undefined) _params['search'] = search;
      if (sortByDate !== undefined) _params['sortByDate'] = sortByDate;
      if (archived !== undefined) _params['archived'] = archived;
      if (builderVersion !== undefined) _params['builderVersion'] = builderVersion;
      if (name !== undefined) _params['name'] = name;
      if (parentId !== undefined) _params['parentId'] = parentId;
      if (originId !== undefined) _params['originId'] = originId;
      if (templatesOnly !== undefined) _params['templatesOnly'] = templatesOnly;
      return request('GET', '/emails/builder', { query: _params });
    },

    /**
     * Create a new template
     * POST /emails/builder
     * @param {object} body — request body
     * @scopes emails/builder.write
     */
    async createTemplate(body) {
      return request('POST', '/emails/builder', { body });
    },

    /**
     * Delete a template
     * DELETE /emails/builder/{locationId}/{templateId}
     * @param {string} locationId
     * @param {string} templateId
     */
    async deleteTemplate(locationId, templateId) {
      return request('DELETE', `/emails/builder/${locationId}/${templateId}`);
    },

    /**
     * Update a template
     * POST /emails/builder/data
     * @param {object} body — request body
     * @scopes emails/builder.write
     */
    async updateTemplate(body) {
      return request('POST', '/emails/builder/data', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  fetchCampaigns: ["emails/schedule.readonly"],
  fetchTemplate: ["emails/builder.readonly"],
  createTemplate: ["emails/builder.write"],
  updateTemplate: ["emails/builder.write"],
};
