/**
 * GHL API — email-isv namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 1 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the email-isv namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all email-isv operations
 */
export function createEmailIsvNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Email Verification
     * POST /email/verify
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {object} body — request body
     */
    async verifyEmail({ locationId } = {}, body) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('POST', '/email/verify', { query: _params, body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
};
