/**
 * GHL API — forms namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 3 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the forms namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all forms operations
 */
export function createFormsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Forms Submissions
     * GET /forms/submissions
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.page]
     * @param {*} [query.limit]
     * @param {*} [query.formId]
     * @param {*} [query.q]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @scopes forms.readonly
     */
    async getFormsSubmissions({ locationId, page, limit, formId, q, startAt, endAt } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (page !== undefined) _params['page'] = page;
      if (limit !== undefined) _params['limit'] = limit;
      if (formId !== undefined) _params['formId'] = formId;
      if (q !== undefined) _params['q'] = q;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      return request('GET', '/forms/submissions', { query: _params });
    },

    /**
     * Upload files to custom fields
     * POST /forms/upload-custom-files
     * @param {object} [query]
     * @param {*} [query.contactId] (required)
     * @param {*} [query.locationId] (required)
     * @param {object} body — request body
     * @scopes forms.write
     */
    async uploadToCustomFields({ contactId, locationId } = {}, body) {
      const _params = {};
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('POST', '/forms/upload-custom-files', { query: _params, body, isMultipart: true });
    },

    /**
     * Get Forms
     * GET /forms/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @param {*} [query.type]
     * @scopes forms.readonly
     */
    async getForms({ locationId, skip, limit, type } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (type !== undefined) _params['type'] = type;
      return request('GET', '/forms/', { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getFormsSubmissions: ["forms.readonly"],
  uploadToCustomFields: ["forms.write"],
  getForms: ["forms.readonly"],
};
