/**
 * GHL API — funnels namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 7 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the funnels namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all funnels operations
 */
export function createFunnelsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Create Redirect
     * POST /funnels/lookup/redirect
     * @param {object} body — request body
     * @scopes funnels/redirect.write
     */
    async createRedirect(body) {
      return request('POST', '/funnels/lookup/redirect', { body });
    },

    /**
     * Update Redirect By Id
     * PATCH /funnels/lookup/redirect/{id}
     * @param {string} id
     * @param {object} body — request body
     * @scopes funnels/redirect.write
     */
    async updateRedirectById(id, body) {
      return request('PATCH', `/funnels/lookup/redirect/${id}`, { body });
    },

    /**
     * Delete Redirect By Id
     * DELETE /funnels/lookup/redirect/{id}
     * @param {string} id
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes funnels/redirect.write
     */
    async deleteRedirectById(id, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('DELETE', `/funnels/lookup/redirect/${id}`, { query: _params });
    },

    /**
     * Fetch List of Redirects
     * GET /funnels/lookup/redirect/list
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @param {*} [query.search]
     * @scopes funnels/redirect.readonly
     */
    async fetchRedirectsList({ locationId, limit, offset, search } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (search !== undefined) _params['search'] = search;
      return request('GET', '/funnels/lookup/redirect/list', { query: _params });
    },

    /**
     * Fetch List of Funnels
     * GET /funnels/funnel/list
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.type]
     * @param {*} [query.category]
     * @param {*} [query.offset]
     * @param {*} [query.limit]
     * @param {*} [query.parentId]
     * @param {*} [query.name]
     */
    async getFunnels({ locationId, type, category, offset, limit, parentId, name } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (type !== undefined) _params['type'] = type;
      if (category !== undefined) _params['category'] = category;
      if (offset !== undefined) _params['offset'] = offset;
      if (limit !== undefined) _params['limit'] = limit;
      if (parentId !== undefined) _params['parentId'] = parentId;
      if (name !== undefined) _params['name'] = name;
      return request('GET', '/funnels/funnel/list', { query: _params });
    },

    /**
     * Fetch list of funnel pages
     * GET /funnels/page
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.funnelId] (required)
     * @param {*} [query.name]
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     */
    async getPagesByFunnelId({ locationId, funnelId, name, limit, offset } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (funnelId !== undefined) _params['funnelId'] = funnelId;
      if (name !== undefined) _params['name'] = name;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/funnels/page', { query: _params });
    },

    /**
     * Fetch count of funnel pages
     * GET /funnels/page/count
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.funnelId] (required)
     * @param {*} [query.name]
     */
    async getPagesCountByFunnelId({ locationId, funnelId, name } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (funnelId !== undefined) _params['funnelId'] = funnelId;
      if (name !== undefined) _params['name'] = name;
      return request('GET', '/funnels/page/count', { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  createRedirect: ["funnels/redirect.write"],
  updateRedirectById: ["funnels/redirect.write"],
  deleteRedirectById: ["funnels/redirect.write"],
  fetchRedirectsList: ["funnels/redirect.readonly"],
};
