/**
 * GHL API — namespace index
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY
 */

export { createAssociationsNamespace } from './associations.mjs';
export { createBlogsNamespace } from './blogs.mjs';
export { createBusinessesNamespace } from './businesses.mjs';
export { createCalendarsNamespace } from './calendars.mjs';
export { createCampaignsNamespace } from './campaigns.mjs';
export { createCompaniesNamespace } from './companies.mjs';
export { createContactsNamespace } from './contacts.mjs';
export { createConversationsNamespace } from './conversations.mjs';
export { createCoursesNamespace } from './courses.mjs';
export { createCustomFieldsNamespace } from './custom-fields.mjs';
export { createCustomMenusNamespace } from './custom-menus.mjs';
export { createEmailIsvNamespace } from './email-isv.mjs';
export { createEmailsNamespace } from './emails.mjs';
export { createFormsNamespace } from './forms.mjs';
export { createFunnelsNamespace } from './funnels.mjs';
export { createInvoicesNamespace } from './invoices.mjs';
export { createLinksNamespace } from './links.mjs';
export { createLocationsNamespace } from './locations.mjs';
export { createMarketplaceNamespace } from './marketplace.mjs';
export { createMediasNamespace } from './medias.mjs';
export { createOauthNamespace } from './oauth.mjs';
export { createObjectsNamespace } from './objects.mjs';
export { createOpportunitiesNamespace } from './opportunities.mjs';
export { createPaymentsNamespace } from './payments.mjs';
export { createPhoneSystemNamespace } from './phone-system.mjs';
export { createProductsNamespace } from './products.mjs';
export { createProposalsNamespace } from './proposals.mjs';
export { createSaasApiNamespace } from './saas-api.mjs';
export { createSnapshotsNamespace } from './snapshots.mjs';
export { createSocialMediaPostingNamespace } from './social-media-posting.mjs';
export { createStoreNamespace } from './store.mjs';
export { createSurveysNamespace } from './surveys.mjs';
export { createUsersNamespace } from './users.mjs';
export { createVoiceAiNamespace } from './voice-ai.mjs';
export { createWorkflowsNamespace } from './workflows.mjs';

/**
 * Lazy-load a namespace factory by name.
 * @param {string} name — namespace name (e.g. 'contacts', 'blogs')
 * @returns {Promise<Function>} factory function
 */
export async function loadNamespace(name) {
  const factories = {
    'associations': () => import('./associations.mjs').then(m => m.createAssociationsNamespace),
    'blogs': () => import('./blogs.mjs').then(m => m.createBlogsNamespace),
    'businesses': () => import('./businesses.mjs').then(m => m.createBusinessesNamespace),
    'calendars': () => import('./calendars.mjs').then(m => m.createCalendarsNamespace),
    'campaigns': () => import('./campaigns.mjs').then(m => m.createCampaignsNamespace),
    'companies': () => import('./companies.mjs').then(m => m.createCompaniesNamespace),
    'contacts': () => import('./contacts.mjs').then(m => m.createContactsNamespace),
    'conversations': () => import('./conversations.mjs').then(m => m.createConversationsNamespace),
    'courses': () => import('./courses.mjs').then(m => m.createCoursesNamespace),
    'customFields': () => import('./custom-fields.mjs').then(m => m.createCustomFieldsNamespace),
    'customMenus': () => import('./custom-menus.mjs').then(m => m.createCustomMenusNamespace),
    'emailIsv': () => import('./email-isv.mjs').then(m => m.createEmailIsvNamespace),
    'emails': () => import('./emails.mjs').then(m => m.createEmailsNamespace),
    'forms': () => import('./forms.mjs').then(m => m.createFormsNamespace),
    'funnels': () => import('./funnels.mjs').then(m => m.createFunnelsNamespace),
    'invoices': () => import('./invoices.mjs').then(m => m.createInvoicesNamespace),
    'links': () => import('./links.mjs').then(m => m.createLinksNamespace),
    'locations': () => import('./locations.mjs').then(m => m.createLocationsNamespace),
    'marketplace': () => import('./marketplace.mjs').then(m => m.createMarketplaceNamespace),
    'medias': () => import('./medias.mjs').then(m => m.createMediasNamespace),
    'oauth': () => import('./oauth.mjs').then(m => m.createOauthNamespace),
    'objects': () => import('./objects.mjs').then(m => m.createObjectsNamespace),
    'opportunities': () => import('./opportunities.mjs').then(m => m.createOpportunitiesNamespace),
    'payments': () => import('./payments.mjs').then(m => m.createPaymentsNamespace),
    'phoneSystem': () => import('./phone-system.mjs').then(m => m.createPhoneSystemNamespace),
    'products': () => import('./products.mjs').then(m => m.createProductsNamespace),
    'proposals': () => import('./proposals.mjs').then(m => m.createProposalsNamespace),
    'saasApi': () => import('./saas-api.mjs').then(m => m.createSaasApiNamespace),
    'snapshots': () => import('./snapshots.mjs').then(m => m.createSnapshotsNamespace),
    'socialMediaPosting': () => import('./social-media-posting.mjs').then(m => m.createSocialMediaPostingNamespace),
    'store': () => import('./store.mjs').then(m => m.createStoreNamespace),
    'surveys': () => import('./surveys.mjs').then(m => m.createSurveysNamespace),
    'users': () => import('./users.mjs').then(m => m.createUsersNamespace),
    'voiceAi': () => import('./voice-ai.mjs').then(m => m.createVoiceAiNamespace),
    'workflows': () => import('./workflows.mjs').then(m => m.createWorkflowsNamespace),
  };
  const loader = factories[name];
  if (!loader) throw new Error(`Unknown GHL namespace: "${name}"`);
  return loader();
}

/** All available namespace names. */
export const NAMESPACE_NAMES = [
  'associations',
  'blogs',
  'businesses',
  'calendars',
  'campaigns',
  'companies',
  'contacts',
  'conversations',
  'courses',
  'customFields',
  'customMenus',
  'emailIsv',
  'emails',
  'forms',
  'funnels',
  'invoices',
  'links',
  'locations',
  'marketplace',
  'medias',
  'oauth',
  'objects',
  'opportunities',
  'payments',
  'phoneSystem',
  'products',
  'proposals',
  'saasApi',
  'snapshots',
  'socialMediaPosting',
  'store',
  'surveys',
  'users',
  'voiceAi',
  'workflows',
];
