/**
 * GHL API — invoices namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 41 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the invoices namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all invoices operations
 */
export function createInvoicesNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * List templates
     * GET /invoices/template
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.status]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @param {*} [query.search]
     * @param {*} [query.paymentMode]
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @scopes invoices/template.readonly
     */
    async listInvoiceTemplates({ altId, altType, status, startAt, endAt, search, paymentMode, limit, offset } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (status !== undefined) _params['status'] = status;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      if (search !== undefined) _params['search'] = search;
      if (paymentMode !== undefined) _params['paymentMode'] = paymentMode;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/invoices/template', { query: _params });
    },

    /**
     * Create template
     * POST /invoices/template
     * @param {object} body — request body
     * @scopes invoices/template.write
     */
    async createInvoiceTemplate(body) {
      return request('POST', '/invoices/template', { body });
    },

    /**
     * Get an template
     * GET /invoices/template/{templateId}
     * @param {string} templateId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices/template.readonly
     */
    async getInvoiceTemplate(templateId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/invoices/template/${templateId}`, { query: _params });
    },

    /**
     * Update template
     * PUT /invoices/template/{templateId}
     * @param {string} templateId
     * @param {object} body — request body
     * @scopes invoices/template.write
     */
    async updateInvoiceTemplate(templateId, body) {
      return request('PUT', `/invoices/template/${templateId}`, { body });
    },

    /**
     * Delete template
     * DELETE /invoices/template/{templateId}
     * @param {string} templateId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices/template.write
     */
    async deleteInvoiceTemplate(templateId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('DELETE', `/invoices/template/${templateId}`, { query: _params });
    },

    /**
     * Update template late fees configuration
     * PATCH /invoices/template/{templateId}/late-fees-configuration
     * @param {string} templateId
     * @param {object} body — request body
     */
    async updateInvoiceTemplateLateFeesConfiguration(templateId, body) {
      return request('PATCH', `/invoices/template/${templateId}/late-fees-configuration`, { body });
    },

    /**
     * Update template late fees configuration
     * PATCH /invoices/template/{templateId}/payment-methods-configuration
     * @param {string} templateId
     * @param {object} body — request body
     */
    async updateInvoicePaymentMethodsConfiguration(templateId, body) {
      return request('PATCH', `/invoices/template/${templateId}/payment-methods-configuration`, { body });
    },

    /**
     * List schedules
     * GET /invoices/schedule
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.status]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @param {*} [query.search]
     * @param {*} [query.paymentMode]
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @scopes invoices/schedule.readonly
     */
    async listInvoiceSchedules({ altId, altType, status, startAt, endAt, search, paymentMode, limit, offset } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (status !== undefined) _params['status'] = status;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      if (search !== undefined) _params['search'] = search;
      if (paymentMode !== undefined) _params['paymentMode'] = paymentMode;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/invoices/schedule', { query: _params });
    },

    /**
     * Create Invoice Schedule
     * POST /invoices/schedule
     * @param {object} body — request body
     * @scopes invoices/schedule.write
     */
    async createInvoiceSchedule(body) {
      return request('POST', '/invoices/schedule', { body });
    },

    /**
     * Get an schedule
     * GET /invoices/schedule/{scheduleId}
     * @param {string} scheduleId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices/schedule.readonly
     */
    async getInvoiceSchedule(scheduleId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/invoices/schedule/${scheduleId}`, { query: _params });
    },

    /**
     * Update schedule
     * PUT /invoices/schedule/{scheduleId}
     * @param {string} scheduleId
     * @param {object} body — request body
     * @scopes invoices/schedule.write
     */
    async updateInvoiceSchedule(scheduleId, body) {
      return request('PUT', `/invoices/schedule/${scheduleId}`, { body });
    },

    /**
     * Delete schedule
     * DELETE /invoices/schedule/{scheduleId}
     * @param {string} scheduleId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices/schedule.write
     */
    async deleteInvoiceSchedule(scheduleId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('DELETE', `/invoices/schedule/${scheduleId}`, { query: _params });
    },

    /**
     * Update scheduled recurring invoice
     * POST /invoices/schedule/{scheduleId}/updateAndSchedule
     * @param {string} scheduleId
     * @scopes invoices/schedule.write
     */
    async updateAndScheduleInvoiceSchedule(scheduleId) {
      return request('POST', `/invoices/schedule/${scheduleId}/updateAndSchedule`);
    },

    /**
     * Schedule an schedule invoice
     * POST /invoices/schedule/{scheduleId}/schedule
     * @param {string} scheduleId
     * @param {object} body — request body
     * @scopes invoices/schedule.write
     */
    async scheduleInvoiceSchedule(scheduleId, body) {
      return request('POST', `/invoices/schedule/${scheduleId}/schedule`, { body });
    },

    /**
     * Manage Auto payment for an schedule invoice
     * POST /invoices/schedule/{scheduleId}/auto-payment
     * @param {string} scheduleId
     * @param {object} body — request body
     * @scopes invoices/schedule.write
     */
    async autoPaymentInvoiceSchedule(scheduleId, body) {
      return request('POST', `/invoices/schedule/${scheduleId}/auto-payment`, { body });
    },

    /**
     * Cancel an scheduled invoice
     * POST /invoices/schedule/{scheduleId}/cancel
     * @param {string} scheduleId
     * @param {object} body — request body
     * @scopes invoices/schedule.write
     */
    async cancelInvoiceSchedule(scheduleId, body) {
      return request('POST', `/invoices/schedule/${scheduleId}/cancel`, { body });
    },

    /**
     * Create & Send
     * POST /invoices/text2pay
     * @param {object} body — request body
     * @scopes invoices.write
     */
    async text2payInvoice(body) {
      return request('POST', '/invoices/text2pay', { body });
    },

    /**
     * Generate Invoice Number
     * GET /invoices/generate-invoice-number
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices.readonly
     */
    async generateInvoiceNumber({ altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', '/invoices/generate-invoice-number', { query: _params });
    },

    /**
     * Get invoice
     * GET /invoices/{invoiceId}
     * @param {string} invoiceId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices.readonly
     */
    async getInvoice(invoiceId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/invoices/${invoiceId}`, { query: _params });
    },

    /**
     * Update invoice
     * PUT /invoices/{invoiceId}
     * @param {string} invoiceId
     * @param {object} body — request body
     * @scopes invoices.write
     */
    async updateInvoice(invoiceId, body) {
      return request('PUT', `/invoices/${invoiceId}`, { body });
    },

    /**
     * Delete invoice
     * DELETE /invoices/{invoiceId}
     * @param {string} invoiceId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices.write
     */
    async deleteInvoice(invoiceId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('DELETE', `/invoices/${invoiceId}`, { query: _params });
    },

    /**
     * Update invoice late fees configuration
     * PATCH /invoices/{invoiceId}/late-fees-configuration
     * @param {string} invoiceId
     * @param {object} body — request body
     */
    async updateInvoiceLateFeesConfiguration(invoiceId, body) {
      return request('PATCH', `/invoices/${invoiceId}/late-fees-configuration`, { body });
    },

    /**
     * Void invoice
     * POST /invoices/{invoiceId}/void
     * @param {string} invoiceId
     * @param {object} body — request body
     * @scopes invoices.write
     */
    async voidInvoice(invoiceId, body) {
      return request('POST', `/invoices/${invoiceId}/void`, { body });
    },

    /**
     * Send invoice
     * POST /invoices/{invoiceId}/send
     * @param {string} invoiceId
     * @param {object} body — request body
     * @scopes invoices.write
     */
    async sendInvoice(invoiceId, body) {
      return request('POST', `/invoices/${invoiceId}/send`, { body });
    },

    /**
     * Record a manual payment for an invoice
     * POST /invoices/{invoiceId}/record-payment
     * @param {string} invoiceId
     * @param {object} body — request body
     * @scopes invoices.write
     */
    async recordInvoice(invoiceId, body) {
      return request('POST', `/invoices/${invoiceId}/record-payment`, { body });
    },

    /**
     * Update invoice last visited at
     * PATCH /invoices/stats/last-visited-at
     * @param {object} body — request body
     */
    async updateInvoiceLastVisitedAt(body) {
      return request('PATCH', '/invoices/stats/last-visited-at', { body });
    },

    /**
     * Create New Estimate
     * POST /invoices/estimate
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async createNewEstimate(body) {
      return request('POST', '/invoices/estimate', { body });
    },

    /**
     * Update Estimate
     * PUT /invoices/estimate/{estimateId}
     * @param {string} estimateId
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async updateEstimate(estimateId, body) {
      return request('PUT', `/invoices/estimate/${estimateId}`, { body });
    },

    /**
     * Delete Estimate
     * DELETE /invoices/estimate/{estimateId}
     * @param {string} estimateId
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async deleteEstimate(estimateId, body) {
      return request('DELETE', `/invoices/estimate/${estimateId}`, { body });
    },

    /**
     * Generate Estimate Number
     * GET /invoices/estimate/number/generate
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes invoices/estimate.readonly
     */
    async generateEstimateNumber({ altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', '/invoices/estimate/number/generate', { query: _params });
    },

    /**
     * Send Estimate
     * POST /invoices/estimate/{estimateId}/send
     * @param {string} estimateId
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async sendEstimate(estimateId, body) {
      return request('POST', `/invoices/estimate/${estimateId}/send`, { body });
    },

    /**
     * Create Invoice from Estimate
     * POST /invoices/estimate/{estimateId}/invoice
     * @param {string} estimateId
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async createInvoiceFromEstimate(estimateId, body) {
      return request('POST', `/invoices/estimate/${estimateId}/invoice`, { body });
    },

    /**
     * List Estimates
     * GET /invoices/estimate/list
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @param {*} [query.search]
     * @param {*} [query.status]
     * @param {*} [query.contactId]
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @scopes invoices/estimate.readonly
     */
    async listEstimates({ altId, altType, startAt, endAt, search, status, contactId, limit, offset } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      if (search !== undefined) _params['search'] = search;
      if (status !== undefined) _params['status'] = status;
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/invoices/estimate/list', { query: _params });
    },

    /**
     * Update estimate last visited at
     * PATCH /invoices/estimate/stats/last-visited-at
     * @param {object} body — request body
     */
    async updateEstimateLastVisitedAt(body) {
      return request('PATCH', '/invoices/estimate/stats/last-visited-at', { body });
    },

    /**
     * List Estimate Templates
     * GET /invoices/estimate/template
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.search]
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @scopes invoices/estimate.readonly
     */
    async listEstimateTemplates({ altId, altType, search, limit, offset } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (search !== undefined) _params['search'] = search;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/invoices/estimate/template', { query: _params });
    },

    /**
     * Create Estimate Template
     * POST /invoices/estimate/template
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async createEstimateTemplate(body) {
      return request('POST', '/invoices/estimate/template', { body });
    },

    /**
     * Update Estimate Template
     * PUT /invoices/estimate/template/{templateId}
     * @param {string} templateId
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async updateEstimateTemplate(templateId, body) {
      return request('PUT', `/invoices/estimate/template/${templateId}`, { body });
    },

    /**
     * Delete Estimate Template
     * DELETE /invoices/estimate/template/{templateId}
     * @param {string} templateId
     * @param {object} body — request body
     * @scopes invoices/estimate.write
     */
    async deleteEstimateTemplate(templateId, body) {
      return request('DELETE', `/invoices/estimate/template/${templateId}`, { body });
    },

    /**
     * Preview Estimate Template
     * GET /invoices/estimate/template/preview
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.templateId] (required)
     * @scopes invoices/estimate.readonly
     */
    async previewEstimateTemplate({ altId, altType, templateId } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (templateId !== undefined) _params['templateId'] = templateId;
      return request('GET', '/invoices/estimate/template/preview', { query: _params });
    },

    /**
     * List invoices
     * GET /invoices/
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.status]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @param {*} [query.search]
     * @param {*} [query.paymentMode]
     * @param {*} [query.contactId]
     * @param {*} [query.limit] (required)
     * @param {*} [query.offset] (required)
     * @param {*} [query.sortField]
     * @param {*} [query.sortOrder]
     * @scopes invoices.readonly
     */
    async listInvoices({ altId, altType, status, startAt, endAt, search, paymentMode, contactId, limit, offset, sortField, sortOrder } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (status !== undefined) _params['status'] = status;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      if (search !== undefined) _params['search'] = search;
      if (paymentMode !== undefined) _params['paymentMode'] = paymentMode;
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (sortField !== undefined) _params['sortField'] = sortField;
      if (sortOrder !== undefined) _params['sortOrder'] = sortOrder;
      return request('GET', '/invoices/', { query: _params });
    },

    /**
     * Create Invoice
     * POST /invoices/
     * @param {object} body — request body
     * @scopes invoices.write
     */
    async createInvoice(body) {
      return request('POST', '/invoices/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  listInvoiceTemplates: ["invoices/template.readonly"],
  createInvoiceTemplate: ["invoices/template.write"],
  getInvoiceTemplate: ["invoices/template.readonly"],
  updateInvoiceTemplate: ["invoices/template.write"],
  deleteInvoiceTemplate: ["invoices/template.write"],
  listInvoiceSchedules: ["invoices/schedule.readonly"],
  createInvoiceSchedule: ["invoices/schedule.write"],
  getInvoiceSchedule: ["invoices/schedule.readonly"],
  updateInvoiceSchedule: ["invoices/schedule.write"],
  deleteInvoiceSchedule: ["invoices/schedule.write"],
  updateAndScheduleInvoiceSchedule: ["invoices/schedule.write"],
  scheduleInvoiceSchedule: ["invoices/schedule.write"],
  autoPaymentInvoiceSchedule: ["invoices/schedule.write"],
  cancelInvoiceSchedule: ["invoices/schedule.write"],
  text2payInvoice: ["invoices.write"],
  generateInvoiceNumber: ["invoices.readonly"],
  getInvoice: ["invoices.readonly"],
  updateInvoice: ["invoices.write"],
  deleteInvoice: ["invoices.write"],
  voidInvoice: ["invoices.write"],
  sendInvoice: ["invoices.write"],
  recordInvoice: ["invoices.write"],
  createNewEstimate: ["invoices/estimate.write"],
  updateEstimate: ["invoices/estimate.write"],
  deleteEstimate: ["invoices/estimate.write"],
  generateEstimateNumber: ["invoices/estimate.readonly"],
  sendEstimate: ["invoices/estimate.write"],
  createInvoiceFromEstimate: ["invoices/estimate.write"],
  listEstimates: ["invoices/estimate.readonly"],
  listEstimateTemplates: ["invoices/estimate.readonly"],
  createEstimateTemplate: ["invoices/estimate.write"],
  updateEstimateTemplate: ["invoices/estimate.write"],
  deleteEstimateTemplate: ["invoices/estimate.write"],
  previewEstimateTemplate: ["invoices/estimate.readonly"],
  listInvoices: ["invoices.readonly"],
  createInvoice: ["invoices.write"],
};
