/**
 * GHL API — links namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 6 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the links namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all links operations
 */
export function createLinksNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Link by ID
     * GET /links/id/{linkId}
     * @param {string} linkId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     */
    async getLinkById(linkId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/links/id/${linkId}`, { query: _params });
    },

    /**
     * Update Link
     * PUT /links/{linkId}
     * @param {string} linkId
     * @param {object} body — request body
     * @scopes links.write
     */
    async updateLink(linkId, body) {
      return request('PUT', `/links/${linkId}`, { body });
    },

    /**
     * Delete Link
     * DELETE /links/{linkId}
     * @param {string} linkId
     * @scopes links.write
     */
    async deleteLink(linkId) {
      return request('DELETE', `/links/${linkId}`);
    },

    /**
     * Search Trigger Links
     * GET /links/search
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.query]
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     */
    async searchTriggerLinks({ locationId, query, skip, limit } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (query !== undefined) _params['query'] = query;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      return request('GET', '/links/search', { query: _params });
    },

    /**
     * Get Links
     * GET /links/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes links.readonly
     */
    async getLinks({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/links/', { query: _params });
    },

    /**
     * Create Link
     * POST /links/
     * @param {object} body — request body
     * @scopes links.write
     */
    async createLink(body) {
      return request('POST', '/links/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  updateLink: ["links.write"],
  deleteLink: ["links.write"],
  getLinks: ["links.readonly"],
  createLink: ["links.write"],
};
