/**
 * GHL API — locations namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 29 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the locations namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all locations operations
 */
export function createLocationsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Search
     * GET /locations/search
     * @param {object} [query]
     * @param {*} [query.companyId]
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @param {*} [query.order]
     * @param {*} [query.email]
     * @scopes locations.readonly
     */
    async searchLocations({ companyId, skip, limit, order, email } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (order !== undefined) _params['order'] = order;
      if (email !== undefined) _params['email'] = email;
      return request('GET', '/locations/search', { query: _params });
    },

    /**
     * Get Sub-Account (Formerly Location)
     * GET /locations/{locationId}
     * @param {string} locationId
     * @scopes locations.readonly
     */
    async getLocation(locationId) {
      return request('GET', `/locations/${locationId}`);
    },

    /**
     * Put Sub-Account (Formerly Location)
     * PUT /locations/{locationId}
     * @param {string} locationId
     * @param {object} body — request body
     * @scopes locations.write
     */
    async putLocation(locationId, body) {
      return request('PUT', `/locations/${locationId}`, { body });
    },

    /**
     * Delete Sub-Account (Formerly Location)
     * DELETE /locations/{locationId}
     * @param {string} locationId
     * @param {object} [query]
     * @param {*} [query.deleteTwilioAccount] (required)
     * @scopes locations.internal-access-only
     */
    async deleteLocation(locationId, { deleteTwilioAccount } = {}) {
      const _params = {};
      if (deleteTwilioAccount !== undefined) _params['deleteTwilioAccount'] = deleteTwilioAccount;
      return request('DELETE', `/locations/${locationId}`, { query: _params });
    },

    /**
     * Get Tags
     * GET /locations/{locationId}/tags
     * @param {string} locationId
     * @scopes locations/tags.readonly
     */
    async getLocationTags(locationId) {
      return request('GET', `/locations/${locationId}/tags`);
    },

    /**
     * Create Tag
     * POST /locations/{locationId}/tags
     * @param {string} locationId
     * @param {object} body — request body
     * @scopes locations/tags.write
     */
    async createTag(locationId, body) {
      return request('POST', `/locations/${locationId}/tags`, { body });
    },

    /**
     * Get tag by id
     * GET /locations/{locationId}/tags/{tagId}
     * @param {string} locationId
     * @param {string} tagId
     */
    async getTagById(locationId, tagId) {
      return request('GET', `/locations/${locationId}/tags/${tagId}`);
    },

    /**
     * Update tag
     * PUT /locations/{locationId}/tags/{tagId}
     * @param {string} locationId
     * @param {string} tagId
     * @param {object} body — request body
     */
    async updateTag(locationId, tagId, body) {
      return request('PUT', `/locations/${locationId}/tags/${tagId}`, { body });
    },

    /**
     * Delete tag
     * DELETE /locations/{locationId}/tags/{tagId}
     * @param {string} locationId
     * @param {string} tagId
     */
    async deleteTag(locationId, tagId) {
      return request('DELETE', `/locations/${locationId}/tags/${tagId}`);
    },

    /**
     * Task Search Filter
     * POST /locations/{locationId}/tasks/search
     * @param {string} locationId
     * @param {object} body — request body
     * @scopes locations/tasks.readonly
     */
    async taskSearch(locationId, body) {
      return request('POST', `/locations/${locationId}/tasks/search`, { body });
    },

    /**
     * Get Recurring Task By Id
     * GET /locations/{locationId}/recurring-tasks/{id}
     * @param {string} id
     * @param {string} locationId
     */
    async getRecurringTaskById(id, locationId) {
      return request('GET', `/locations/${locationId}/recurring-tasks/${id}`);
    },

    /**
     * Update Recurring Task
     * PUT /locations/{locationId}/recurring-tasks/{id}
     * @param {string} id
     * @param {string} locationId
     * @param {object} body — request body
     */
    async updateRecurringTask(id, locationId, body) {
      return request('PUT', `/locations/${locationId}/recurring-tasks/${id}`, { body });
    },

    /**
     * Delete Recurring Task
     * DELETE /locations/{locationId}/recurring-tasks/{id}
     * @param {string} id
     * @param {string} locationId
     */
    async deleteRecurringTask(id, locationId) {
      return request('DELETE', `/locations/${locationId}/recurring-tasks/${id}`);
    },

    /**
     * Create Recurring Task
     * POST /locations/{locationId}/recurring-tasks
     * @param {string} locationId
     * @param {object} body — request body
     */
    async createRecurringTask(locationId, body) {
      return request('POST', `/locations/${locationId}/recurring-tasks`, { body });
    },

    /**
     * Get Custom Fields
     * GET /locations/{locationId}/customFields
     * @param {string} locationId
     * @param {object} [query]
     * @param {*} [query.model]
     * @scopes locations/customFields.readonly
     */
    async getCustomFields(locationId, { model } = {}) {
      const _params = {};
      if (model !== undefined) _params['model'] = model;
      return request('GET', `/locations/${locationId}/customFields`, { query: _params });
    },

    /**
     * Create Custom Field
     * POST /locations/{locationId}/customFields
     * @param {string} locationId
     * @param {object} body — request body
     * @scopes locations/customFields.write
     */
    async createCustomField(locationId, body) {
      return request('POST', `/locations/${locationId}/customFields`, { body });
    },

    /**
     * Get Custom Field
     * GET /locations/{locationId}/customFields/{id}
     * @param {string} locationId
     * @param {string} id
     */
    async getCustomField(locationId, id) {
      return request('GET', `/locations/${locationId}/customFields/${id}`);
    },

    /**
     * Update Custom Field
     * PUT /locations/{locationId}/customFields/{id}
     * @param {string} locationId
     * @param {string} id
     * @param {object} body — request body
     */
    async updateCustomField(locationId, id, body) {
      return request('PUT', `/locations/${locationId}/customFields/${id}`, { body });
    },

    /**
     * Delete Custom Field
     * DELETE /locations/{locationId}/customFields/{id}
     * @param {string} locationId
     * @param {string} id
     */
    async deleteCustomField(locationId, id) {
      return request('DELETE', `/locations/${locationId}/customFields/${id}`);
    },

    /**
     * Uploads File to customFields
     * POST /locations/{locationId}/customFields/upload
     * @param {string} locationId
     * @param {object} body — request body
     * @scopes locations/customFields.write
     */
    async uploadFileCustomFields(locationId, body) {
      return request('POST', `/locations/${locationId}/customFields/upload`, { body, isMultipart: true });
    },

    /**
     * Get Custom Values
     * GET /locations/{locationId}/customValues
     * @param {string} locationId
     * @scopes locations/customValues.readonly
     */
    async getCustomValues(locationId) {
      return request('GET', `/locations/${locationId}/customValues`);
    },

    /**
     * Create Custom Value
     * POST /locations/{locationId}/customValues
     * @param {string} locationId
     * @param {object} body — request body
     * @scopes locations/customValues.write
     */
    async createCustomValue(locationId, body) {
      return request('POST', `/locations/${locationId}/customValues`, { body });
    },

    /**
     * Get Custom Value
     * GET /locations/{locationId}/customValues/{id}
     * @param {string} locationId
     * @param {string} id
     */
    async getCustomValue(locationId, id) {
      return request('GET', `/locations/${locationId}/customValues/${id}`);
    },

    /**
     * Update Custom Value
     * PUT /locations/{locationId}/customValues/{id}
     * @param {string} locationId
     * @param {string} id
     * @param {object} body — request body
     */
    async updateCustomValue(locationId, id, body) {
      return request('PUT', `/locations/${locationId}/customValues/${id}`, { body });
    },

    /**
     * Delete Custom Value
     * DELETE /locations/{locationId}/customValues/{id}
     * @param {string} locationId
     * @param {string} id
     */
    async deleteCustomValue(locationId, id) {
      return request('DELETE', `/locations/${locationId}/customValues/${id}`);
    },

    /**
     * Fetch Timezones
     * GET /locations/{locationId}/timezones
     * @param {string} locationId
     * @scopes locations.readonly
     */
    async getTimezones(locationId) {
      return request('GET', `/locations/${locationId}/timezones`);
    },

    /**
     * GET all or email/sms templates
     * GET /locations/{locationId}/templates
     * @param {string} locationId
     * @param {object} [query]
     * @param {*} [query.deleted]
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @param {*} [query.type]
     * @param {*} [query.originId] (required)
     * @scopes locations/templates.readonly
     */
    async gETAllOrEmailSmsTemplates(locationId, { deleted, skip, limit, type, originId } = {}) {
      const _params = {};
      if (deleted !== undefined) _params['deleted'] = deleted;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (type !== undefined) _params['type'] = type;
      if (originId !== undefined) _params['originId'] = originId;
      return request('GET', `/locations/${locationId}/templates`, { query: _params });
    },

    /**
     * DELETE an email/sms template
     * DELETE /locations/{locationId}/templates/{id}
     * @param {string} locationId
     * @param {string} id
     */
    async dELETEAnEmailSmsTemplate(locationId, id) {
      return request('DELETE', `/locations/${locationId}/templates/${id}`);
    },

    /**
     * Create Sub-Account (Formerly Location)
     * POST /locations/
     * @param {object} body — request body
     * @scopes locations.write
     */
    async createLocation(body) {
      return request('POST', '/locations/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  searchLocations: ["locations.readonly"],
  getLocation: ["locations.readonly"],
  putLocation: ["locations.write"],
  deleteLocation: ["locations.internal-access-only"],
  getLocationTags: ["locations/tags.readonly"],
  createTag: ["locations/tags.write"],
  taskSearch: ["locations/tasks.readonly"],
  getCustomFields: ["locations/customFields.readonly"],
  createCustomField: ["locations/customFields.write"],
  uploadFileCustomFields: ["locations/customFields.write"],
  getCustomValues: ["locations/customValues.readonly"],
  createCustomValue: ["locations/customValues.write"],
  getTimezones: ["locations.readonly"],
  gETAllOrEmailSmsTemplates: ["locations/templates.readonly"],
  createLocation: ["locations.write"],
};
