/**
 * GHL API — marketplace namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 7 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the marketplace namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all marketplace operations
 */
export function createMarketplaceNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get all wallet charges
     * GET /marketplace/billing/charges
     * @param {object} [query]
     * @param {*} [query.meterId]
     * @param {*} [query.eventId]
     * @param {*} [query.userId]
     * @param {*} [query.startDate]
     * @param {*} [query.endDate]
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @scopes charges.readonly
     */
    async getCharges({ meterId, eventId, userId, startDate, endDate, skip, limit } = {}) {
      const _params = {};
      if (meterId !== undefined) _params['meterId'] = meterId;
      if (eventId !== undefined) _params['eventId'] = eventId;
      if (userId !== undefined) _params['userId'] = userId;
      if (startDate !== undefined) _params['startDate'] = startDate;
      if (endDate !== undefined) _params['endDate'] = endDate;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      return request('GET', '/marketplace/billing/charges', { query: _params });
    },

    /**
     * Create a new wallet charge
     * POST /marketplace/billing/charges
     * @param {object} body — request body
     * @scopes charges.write
     */
    async charge(body) {
      return request('POST', '/marketplace/billing/charges', { body });
    },

    /**
     * Get specific wallet charge details
     * GET /marketplace/billing/charges/{chargeId}
     * @param {string} chargeId
     * @scopes charges.readonly
     */
    async getSpecificCharge(chargeId) {
      return request('GET', `/marketplace/billing/charges/${chargeId}`);
    },

    /**
     * Delete a wallet charge
     * DELETE /marketplace/billing/charges/{chargeId}
     * @param {string} chargeId
     * @scopes charges.write
     */
    async deleteCharge(chargeId) {
      return request('DELETE', `/marketplace/billing/charges/${chargeId}`);
    },

    /**
     * Check if account has sufficient funds
     * GET /marketplace/billing/charges/has-funds
     * @scopes charges.readonly
     */
    async hasFunds() {
      return request('GET', '/marketplace/billing/charges/has-funds');
    },

    /**
     * Get Installer Details
     * GET /marketplace/app/{appId}/installations
     * @param {string} appId
     */
    async getInstallerDetails(appId) {
      return request('GET', `/marketplace/app/${appId}/installations`);
    },

    /**
     * Uninstall an application
     * DELETE /marketplace/app/{appId}/installations
     * @param {string} appId
     * @param {object} body — request body
     */
    async uninstallApplication(appId, body) {
      return request('DELETE', `/marketplace/app/${appId}/installations`, { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getCharges: ["charges.readonly"],
  charge: ["charges.write"],
  getSpecificCharge: ["charges.readonly"],
  deleteCharge: ["charges.write"],
  hasFunds: ["charges.readonly"],
};
