/**
 * GHL API — medias namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 7 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the medias namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all medias operations
 */
export function createMediasNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get List of Files/ Folders
     * GET /medias/files
     * @param {object} [query]
     * @param {*} [query.offset]
     * @param {*} [query.limit]
     * @param {*} [query.sortBy] (required)
     * @param {*} [query.sortOrder] (required)
     * @param {*} [query.type] (required)
     * @param {*} [query.query]
     * @param {*} [query.altType] (required)
     * @param {*} [query.altId] (required)
     * @param {*} [query.parentId]
     * @param {*} [query.fetchAll]
     * @scopes medias.readonly
     */
    async fetchMediaContent({ offset, limit, sortBy, sortOrder, type, query, altType, altId, parentId, fetchAll } = {}) {
      const _params = {};
      if (offset !== undefined) _params['offset'] = offset;
      if (limit !== undefined) _params['limit'] = limit;
      if (sortBy !== undefined) _params['sortBy'] = sortBy;
      if (sortOrder !== undefined) _params['sortOrder'] = sortOrder;
      if (type !== undefined) _params['type'] = type;
      if (query !== undefined) _params['query'] = query;
      if (altType !== undefined) _params['altType'] = altType;
      if (altId !== undefined) _params['altId'] = altId;
      if (parentId !== undefined) _params['parentId'] = parentId;
      if (fetchAll !== undefined) _params['fetchAll'] = fetchAll;
      return request('GET', '/medias/files', { query: _params });
    },

    /**
     * Upload File into Media Library
     * POST /medias/upload-file
     * @param {object} body — request body
     * @scopes medias.write
     */
    async uploadMediaContent(body) {
      return request('POST', '/medias/upload-file', { body, isMultipart: true });
    },

    /**
     * Update File/ Folder
     * POST /medias/{id}
     * @param {string} id
     * @param {object} body — request body
     */
    async updateMediaObject(id, body) {
      return request('POST', `/medias/${id}`, { body });
    },

    /**
     * Delete File or Folder
     * DELETE /medias/{id}
     * @param {string} id
     * @param {object} [query]
     * @param {*} [query.altType] (required)
     * @param {*} [query.altId] (required)
     * @scopes medias.write
     */
    async deleteMediaContent(id, { altType, altId } = {}) {
      const _params = {};
      if (altType !== undefined) _params['altType'] = altType;
      if (altId !== undefined) _params['altId'] = altId;
      return request('DELETE', `/medias/${id}`, { query: _params });
    },

    /**
     * Create Folder
     * POST /medias/folder
     * @param {object} body — request body
     */
    async createMediaFolder(body) {
      return request('POST', '/medias/folder', { body });
    },

    /**
     * Bulk Update Files/ Folders
     * PUT /medias/update-files
     * @param {object} body — request body
     */
    async bulkUpdateMediaObjects(body) {
      return request('PUT', '/medias/update-files', { body });
    },

    /**
     * Bulk Delete / Trash Files or Folders
     * PUT /medias/delete-files
     * @param {object} body — request body
     */
    async bulkDeleteMediaObjects(body) {
      return request('PUT', '/medias/delete-files', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  fetchMediaContent: ["medias.readonly"],
  uploadMediaContent: ["medias.write"],
  deleteMediaContent: ["medias.write"],
};
