/**
 * GHL API — oauth namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 3 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the oauth namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all oauth operations
 */
export function createOauthNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Access Token
     * POST /oauth/token
     * @param {object} body — request body
     */
    async getAccessToken(body) {
      return request('POST', '/oauth/token', { body });
    },

    /**
     * Get Location Access Token from Agency Token
     * POST /oauth/locationToken
     * @param {object} body — request body
     * @scopes oauth.write
     */
    async getLocationAccessToken(body) {
      return request('POST', '/oauth/locationToken', { body });
    },

    /**
     * Get Location where app is installed
     * GET /oauth/installedLocations
     * @param {object} [query]
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @param {*} [query.query]
     * @param {*} [query.isInstalled]
     * @param {*} [query.companyId] (required)
     * @param {*} [query.appId] (required)
     * @param {*} [query.versionId]
     * @param {*} [query.onTrial]
     * @param {*} [query.planId]
     * @scopes oauth.readonly
     */
    async getInstalledLocation({ skip, limit, query, isInstalled, companyId, appId, versionId, onTrial, planId } = {}) {
      const _params = {};
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (query !== undefined) _params['query'] = query;
      if (isInstalled !== undefined) _params['isInstalled'] = isInstalled;
      if (companyId !== undefined) _params['companyId'] = companyId;
      if (appId !== undefined) _params['appId'] = appId;
      if (versionId !== undefined) _params['versionId'] = versionId;
      if (onTrial !== undefined) _params['onTrial'] = onTrial;
      if (planId !== undefined) _params['planId'] = planId;
      return request('GET', '/oauth/installedLocations', { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getLocationAccessToken: ["oauth.write"],
  getInstalledLocation: ["oauth.readonly"],
};
