/**
 * GHL API — objects namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 9 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the objects namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all objects operations
 */
export function createObjectsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Object Schema by key / id
     * GET /objects/{key}
     * @param {string} key
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.fetchProperties]
     * @scopes objects/schema.readonly
     */
    async getObjectSchemaByKey(key, { locationId, fetchProperties } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (fetchProperties !== undefined) _params['fetchProperties'] = fetchProperties;
      return request('GET', `/objects/${key}`, { query: _params });
    },

    /**
     * Update Object Schema By Key / Id
     * PUT /objects/{key}
     * @param {string} key
     * @param {object} body — request body
     * @scopes objects/schema.write
     */
    async updateCustomObject(key, body) {
      return request('PUT', `/objects/${key}`, { body });
    },

    /**
     * Get Record By Id
     * GET /objects/{schemaKey}/records/{id}
     * @param {string} schemaKey
     * @param {string} id
     */
    async getRecordById(schemaKey, id) {
      return request('GET', `/objects/${schemaKey}/records/${id}`);
    },

    /**
     * Update Record
     * PUT /objects/{schemaKey}/records/{id}
     * @param {string} schemaKey
     * @param {string} id
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {object} body — request body
     */
    async updateObjectRecord(schemaKey, id, { locationId } = {}, body) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('PUT', `/objects/${schemaKey}/records/${id}`, { query: _params, body });
    },

    /**
     * Delete Record
     * DELETE /objects/{schemaKey}/records/{id}
     * @param {string} schemaKey
     * @param {string} id
     */
    async deleteObjectRecord(schemaKey, id) {
      return request('DELETE', `/objects/${schemaKey}/records/${id}`);
    },

    /**
     * Create Record
     * POST /objects/{schemaKey}/records
     * @param {string} schemaKey
     * @param {object} body — request body
     * @scopes objects/record.write
     */
    async createObjectRecord(schemaKey, body) {
      return request('POST', `/objects/${schemaKey}/records`, { body });
    },

    /**
     * Search Object Records
     * POST /objects/{schemaKey}/records/search
     * @param {string} schemaKey
     * @param {object} body — request body
     * @scopes objects/record.readonly
     */
    async searchObjectRecords(schemaKey, body) {
      return request('POST', `/objects/${schemaKey}/records/search`, { body });
    },

    /**
     * Get all objects for a location
     * GET /objects/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes objects/schema.readonly
     */
    async getObjectByLocationId({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/objects/', { query: _params });
    },

    /**
     * Create Custom Object
     * POST /objects/
     * @param {object} body — request body
     * @scopes objects/schema.write
     */
    async createCustomObjectSchema(body) {
      return request('POST', '/objects/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getObjectSchemaByKey: ["objects/schema.readonly"],
  updateCustomObject: ["objects/schema.write"],
  createObjectRecord: ["objects/record.write"],
  searchObjectRecords: ["objects/record.readonly"],
  getObjectByLocationId: ["objects/schema.readonly"],
  createCustomObjectSchema: ["objects/schema.write"],
};
