/**
 * GHL API — opportunities namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 10 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the opportunities namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all opportunities operations
 */
export function createOpportunitiesNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Search Opportunity
     * GET /opportunities/search
     * @param {object} [query]
     * @param {*} [query.q]
     * @param {*} [query.location_id] (required)
     * @param {*} [query.pipeline_id]
     * @param {*} [query.pipeline_stage_id]
     * @param {*} [query.contact_id]
     * @param {*} [query.status]
     * @param {*} [query.assigned_to]
     * @param {*} [query.campaignId]
     * @param {*} [query.id]
     * @param {*} [query.order]
     * @param {*} [query.endDate]
     * @param {*} [query.startAfter]
     * @param {*} [query.startAfterId]
     * @param {*} [query.date]
     * @param {*} [query.country]
     * @param {*} [query.page]
     * @param {*} [query.limit]
     * @param {*} [query.getTasks]
     * @param {*} [query.getNotes]
     * @param {*} [query.getCalendarEvents]
     * @scopes opportunities.readonly
     */
    async searchOpportunity({ q, location_id, pipeline_id, pipeline_stage_id, contact_id, status, assigned_to, campaignId, id, order, endDate, startAfter, startAfterId, date, country, page, limit, getTasks, getNotes, getCalendarEvents } = {}) {
      const _params = {};
      if (q !== undefined) _params['q'] = q;
      if (location_id !== undefined) _params['location_id'] = location_id;
      if (pipeline_id !== undefined) _params['pipeline_id'] = pipeline_id;
      if (pipeline_stage_id !== undefined) _params['pipeline_stage_id'] = pipeline_stage_id;
      if (contact_id !== undefined) _params['contact_id'] = contact_id;
      if (status !== undefined) _params['status'] = status;
      if (assigned_to !== undefined) _params['assigned_to'] = assigned_to;
      if (campaignId !== undefined) _params['campaignId'] = campaignId;
      if (id !== undefined) _params['id'] = id;
      if (order !== undefined) _params['order'] = order;
      if (endDate !== undefined) _params['endDate'] = endDate;
      if (startAfter !== undefined) _params['startAfter'] = startAfter;
      if (startAfterId !== undefined) _params['startAfterId'] = startAfterId;
      if (date !== undefined) _params['date'] = date;
      if (country !== undefined) _params['country'] = country;
      if (page !== undefined) _params['page'] = page;
      if (limit !== undefined) _params['limit'] = limit;
      if (getTasks !== undefined) _params['getTasks'] = getTasks;
      if (getNotes !== undefined) _params['getNotes'] = getNotes;
      if (getCalendarEvents !== undefined) _params['getCalendarEvents'] = getCalendarEvents;
      return request('GET', '/opportunities/search', { query: _params });
    },

    /**
     * Get Pipelines
     * GET /opportunities/pipelines
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes opportunities.readonly
     */
    async getPipelines({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/opportunities/pipelines', { query: _params });
    },

    /**
     * Get Opportunity
     * GET /opportunities/{id}
     * @param {string} id
     * @scopes opportunities.readonly
     */
    async getOpportunity(id) {
      return request('GET', `/opportunities/${id}`);
    },

    /**
     * Update Opportunity
     * PUT /opportunities/{id}
     * @param {string} id
     * @param {object} body — request body
     * @scopes opportunities.write
     */
    async updateOpportunity(id, body) {
      return request('PUT', `/opportunities/${id}`, { body });
    },

    /**
     * Delete Opportunity
     * DELETE /opportunities/{id}
     * @param {string} id
     * @scopes opportunities.write
     */
    async deleteOpportunity(id) {
      return request('DELETE', `/opportunities/${id}`);
    },

    /**
     * Update Opportunity Status
     * PUT /opportunities/{id}/status
     * @param {string} id
     * @param {object} body — request body
     * @scopes opportunities.write
     */
    async updateOpportunityStatus(id, body) {
      return request('PUT', `/opportunities/${id}/status`, { body });
    },

    /**
     * Upsert Opportunity
     * POST /opportunities/upsert
     * @param {object} body — request body
     * @scopes opportunities.write
     */
    async upsertOpportunity(body) {
      return request('POST', '/opportunities/upsert', { body });
    },

    /**
     * Add Followers
     * POST /opportunities/{id}/followers
     * @param {string} id
     * @param {object} body — request body
     * @scopes opportunities.write
     */
    async addFollowersOpportunity(id, body) {
      return request('POST', `/opportunities/${id}/followers`, { body });
    },

    /**
     * Remove Followers
     * DELETE /opportunities/{id}/followers
     * @param {string} id
     * @param {object} body — request body
     * @scopes opportunities.write
     */
    async removeFollowersOpportunity(id, body) {
      return request('DELETE', `/opportunities/${id}/followers`, { body });
    },

    /**
     * Create Opportunity
     * POST /opportunities/
     * @param {object} body — request body
     * @scopes opportunities.write
     */
    async createOpportunity(body) {
      return request('POST', '/opportunities/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  searchOpportunity: ["opportunities.readonly"],
  getPipelines: ["opportunities.readonly"],
  getOpportunity: ["opportunities.readonly"],
  updateOpportunity: ["opportunities.write"],
  deleteOpportunity: ["opportunities.write"],
  updateOpportunityStatus: ["opportunities.write"],
  upsertOpportunity: ["opportunities.write"],
  addFollowersOpportunity: ["opportunities.write"],
  removeFollowersOpportunity: ["opportunities.write"],
  createOpportunity: ["opportunities.write"],
};
