/**
 * GHL API — payments namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 24 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the payments namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all payments operations
 */
export function createPaymentsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * List White-label Integration Providers
     * GET /payments/integrations/provider/whitelabel
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @scopes payments/integration.readonly
     */
    async listIntegrationProviders({ altId, altType, limit, offset } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/payments/integrations/provider/whitelabel', { query: _params });
    },

    /**
     * Create White-label Integration Provider
     * POST /payments/integrations/provider/whitelabel
     * @param {object} body — request body
     * @scopes payments/integration.write
     */
    async createIntegrationProvider(body) {
      return request('POST', '/payments/integrations/provider/whitelabel', { body });
    },

    /**
     * List Orders
     * GET /payments/orders
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.status]
     * @param {*} [query.paymentMode]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @param {*} [query.search]
     * @param {*} [query.contactId]
     * @param {*} [query.funnelProductIds]
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @scopes payments/orders.readonly
     */
    async listOrders({ locationId, altId, altType, status, paymentMode, startAt, endAt, search, contactId, funnelProductIds, limit, offset } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (status !== undefined) _params['status'] = status;
      if (paymentMode !== undefined) _params['paymentMode'] = paymentMode;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      if (search !== undefined) _params['search'] = search;
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (funnelProductIds !== undefined) _params['funnelProductIds'] = funnelProductIds;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/payments/orders', { query: _params });
    },

    /**
     * Get Order by ID
     * GET /payments/orders/{orderId}
     * @param {string} orderId
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @param {*} [query.altId] (required)
     * @scopes payments/orders.readonly
     */
    async getOrderById(orderId, { locationId, altId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (altId !== undefined) _params['altId'] = altId;
      return request('GET', `/payments/orders/${orderId}`, { query: _params });
    },

    /**
     * Record Order Payment
     * POST /payments/orders/{orderId}/record-payment
     * @param {string} orderId
     * @param {object} body — request body
     * @scopes payments/orders.collectPayment
     */
    async recordOrderPayment(orderId, body) {
      return request('POST', `/payments/orders/${orderId}/record-payment`, { body });
    },

    /**
     * migration Endpoint for Order Payment Status
     * POST /payments/orders/migrate-order-ps
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @param {*} [query.altId] (required)
     */
    async postMigrateOrderPaymentStatus({ locationId, altId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (altId !== undefined) _params['altId'] = altId;
      return request('POST', '/payments/orders/migrate-order-ps', { query: _params });
    },

    /**
     * List fulfillment
     * GET /payments/orders/{orderId}/fulfillments
     * @param {string} orderId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes payments/orders.readonly
     */
    async listOrderFulfillment(orderId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/payments/orders/${orderId}/fulfillments`, { query: _params });
    },

    /**
     * Create order fulfillment
     * POST /payments/orders/{orderId}/fulfillments
     * @param {string} orderId
     * @param {object} body — request body
     * @scopes payments/orders.write
     */
    async createOrderFulfillment(orderId, body) {
      return request('POST', `/payments/orders/${orderId}/fulfillments`, { body });
    },

    /**
     * List Order Notes
     * GET /payments/orders/{orderId}/notes
     * @param {string} orderId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async listOrderNotes(orderId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/payments/orders/${orderId}/notes`, { query: _params });
    },

    /**
     * List Transactions
     * GET /payments/transactions
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.paymentMode]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @param {*} [query.entitySourceType]
     * @param {*} [query.entitySourceSubType]
     * @param {*} [query.search]
     * @param {*} [query.subscriptionId]
     * @param {*} [query.entityId]
     * @param {*} [query.contactId]
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @scopes payments/transactions.readonly
     */
    async listTransactions({ locationId, altId, altType, paymentMode, startAt, endAt, entitySourceType, entitySourceSubType, search, subscriptionId, entityId, contactId, limit, offset } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (paymentMode !== undefined) _params['paymentMode'] = paymentMode;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      if (entitySourceType !== undefined) _params['entitySourceType'] = entitySourceType;
      if (entitySourceSubType !== undefined) _params['entitySourceSubType'] = entitySourceSubType;
      if (search !== undefined) _params['search'] = search;
      if (subscriptionId !== undefined) _params['subscriptionId'] = subscriptionId;
      if (entityId !== undefined) _params['entityId'] = entityId;
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/payments/transactions', { query: _params });
    },

    /**
     * Get Transaction by ID
     * GET /payments/transactions/{transactionId}
     * @param {string} transactionId
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes payments/transactions.readonly
     */
    async getTransactionById(transactionId, { locationId, altId, altType } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/payments/transactions/${transactionId}`, { query: _params });
    },

    /**
     * List Subscriptions
     * GET /payments/subscriptions
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.entityId]
     * @param {*} [query.paymentMode]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @param {*} [query.entitySourceType]
     * @param {*} [query.search]
     * @param {*} [query.contactId]
     * @param {*} [query.id]
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @scopes payments/subscriptions.readonly
     */
    async listSubscriptions({ altId, altType, entityId, paymentMode, startAt, endAt, entitySourceType, search, contactId, id, limit, offset } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (entityId !== undefined) _params['entityId'] = entityId;
      if (paymentMode !== undefined) _params['paymentMode'] = paymentMode;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      if (entitySourceType !== undefined) _params['entitySourceType'] = entitySourceType;
      if (search !== undefined) _params['search'] = search;
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (id !== undefined) _params['id'] = id;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', '/payments/subscriptions', { query: _params });
    },

    /**
     * Get Subscription by ID
     * GET /payments/subscriptions/{subscriptionId}
     * @param {string} subscriptionId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes payments/subscriptions.readonly
     */
    async getSubscriptionById(subscriptionId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/payments/subscriptions/${subscriptionId}`, { query: _params });
    },

    /**
     * List Coupons
     * GET /payments/coupon/list
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.status]
     * @param {*} [query.search]
     * @scopes payments/coupons.readonly
     */
    async listCoupons({ altId, altType, limit, offset, status, search } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (status !== undefined) _params['status'] = status;
      if (search !== undefined) _params['search'] = search;
      return request('GET', '/payments/coupon/list', { query: _params });
    },

    /**
     * Fetch Coupon
     * GET /payments/coupon
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.id] (required)
     * @param {*} [query.code] (required)
     * @scopes payments/coupons.readonly
     */
    async getCoupon({ altId, altType, id, code } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (id !== undefined) _params['id'] = id;
      if (code !== undefined) _params['code'] = code;
      return request('GET', '/payments/coupon', { query: _params });
    },

    /**
     * Create Coupon
     * POST /payments/coupon
     * @param {object} body — request body
     * @scopes payments/coupons.write
     */
    async createCoupon(body) {
      return request('POST', '/payments/coupon', { body });
    },

    /**
     * Update Coupon
     * PUT /payments/coupon
     * @param {object} body — request body
     * @scopes payments/coupons.write
     */
    async updateCoupon(body) {
      return request('PUT', '/payments/coupon', { body });
    },

    /**
     * Delete Coupon
     * DELETE /payments/coupon
     * @param {object} body — request body
     * @scopes payments/coupons.write
     */
    async deleteCoupon(body) {
      return request('DELETE', '/payments/coupon', { body });
    },

    /**
     * Create new integration
     * POST /payments/custom-provider/provider
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {object} body — request body
     * @scopes payments/custom-provider.write
     */
    async createIntegration({ locationId } = {}, body) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('POST', '/payments/custom-provider/provider', { query: _params, body });
    },

    /**
     * Deleting an existing integration
     * DELETE /payments/custom-provider/provider
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes payments/custom-provider.write
     */
    async deleteIntegration({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('DELETE', '/payments/custom-provider/provider', { query: _params });
    },

    /**
     * Fetch given provider config
     * GET /payments/custom-provider/connect
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes payments/custom-provider.readonly
     */
    async fetchConfig({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/payments/custom-provider/connect', { query: _params });
    },

    /**
     * Create new provider config
     * POST /payments/custom-provider/connect
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {object} body — request body
     * @scopes payments/custom-provider.write
     */
    async createConfig({ locationId } = {}, body) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('POST', '/payments/custom-provider/connect', { query: _params, body });
    },

    /**
     * Disconnect existing provider config
     * POST /payments/custom-provider/disconnect
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {object} body — request body
     * @scopes payments/custom-provider.write
     */
    async disconnectConfig({ locationId } = {}, body) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('POST', '/payments/custom-provider/disconnect', { query: _params, body });
    },

    /**
     * Custom-provider marketplace app update capabilities
     * PUT /payments/custom-provider/capabilities
     * @param {object} body — request body
     * @scopes payments/custom-provider.write
     */
    async customProviderMarketplaceAppUpdateCapabilities(body) {
      return request('PUT', '/payments/custom-provider/capabilities', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  listIntegrationProviders: ["payments/integration.readonly"],
  createIntegrationProvider: ["payments/integration.write"],
  listOrders: ["payments/orders.readonly"],
  getOrderById: ["payments/orders.readonly"],
  recordOrderPayment: ["payments/orders.collectPayment"],
  listOrderFulfillment: ["payments/orders.readonly"],
  createOrderFulfillment: ["payments/orders.write"],
  listTransactions: ["payments/transactions.readonly"],
  getTransactionById: ["payments/transactions.readonly"],
  listSubscriptions: ["payments/subscriptions.readonly"],
  getSubscriptionById: ["payments/subscriptions.readonly"],
  listCoupons: ["payments/coupons.readonly"],
  getCoupon: ["payments/coupons.readonly"],
  createCoupon: ["payments/coupons.write"],
  updateCoupon: ["payments/coupons.write"],
  deleteCoupon: ["payments/coupons.write"],
  createIntegration: ["payments/custom-provider.write"],
  deleteIntegration: ["payments/custom-provider.write"],
  fetchConfig: ["payments/custom-provider.readonly"],
  createConfig: ["payments/custom-provider.write"],
  disconnectConfig: ["payments/custom-provider.write"],
  customProviderMarketplaceAppUpdateCapabilities: ["payments/custom-provider.write"],
};
