/**
 * GHL API — phone-system namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 2 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the phone-system namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all phone-system operations
 */
export function createPhoneSystemNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * List Number Pools
     * GET /phone-system/number-pools
     * @param {object} [query]
     * @param {*} [query.locationId]
     * @scopes numberpools.read
     */
    async getNumberPoolList({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/phone-system/number-pools', { query: _params });
    },

    /**
     * List active numbers
     * GET /phone-system/numbers/location/{locationId}
     * @param {string} locationId
     * @param {object} [query]
     * @param {*} [query.pageSize]
     * @param {*} [query.page]
     * @param {*} [query.searchFilter]
     * @param {*} [query.skipNumberPool]
     * @scopes phonenumbers.read
     */
    async activeNumbers(locationId, { pageSize, page, searchFilter, skipNumberPool } = {}) {
      const _params = {};
      if (pageSize !== undefined) _params['pageSize'] = pageSize;
      if (page !== undefined) _params['page'] = page;
      if (searchFilter !== undefined) _params['searchFilter'] = searchFilter;
      if (skipNumberPool !== undefined) _params['skipNumberPool'] = skipNumberPool;
      return request('GET', `/phone-system/numbers/location/${locationId}`, { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getNumberPoolList: ["numberpools.read"],
  activeNumbers: ["phonenumbers.read"],
};
