/**
 * GHL API — products namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 27 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the products namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all products operations
 */
export function createProductsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Bulk Update Products
     * POST /products/bulk-update
     * @param {object} body — request body
     * @scopes products.write
     */
    async bulkUpdate(body) {
      return request('POST', '/products/bulk-update', { body });
    },

    /**
     * Bulk Edit Products and Prices
     * POST /products/bulk-update/edit
     * @param {object} body — request body
     */
    async bulkEdit(body) {
      return request('POST', '/products/bulk-update/edit', { body });
    },

    /**
     * List Prices for a Product
     * GET /products/{productId}/price
     * @param {string} productId
     * @param {object} [query]
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.ids]
     * @scopes products/prices.readonly
     */
    async listPricesForProduct(productId, { limit, offset, locationId, ids } = {}) {
      const _params = {};
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (ids !== undefined) _params['ids'] = ids;
      return request('GET', `/products/${productId}/price`, { query: _params });
    },

    /**
     * Create Price for a Product
     * POST /products/{productId}/price
     * @param {string} productId
     * @param {object} body — request body
     * @scopes products/prices.write
     */
    async createPriceForProduct(productId, body) {
      return request('POST', `/products/${productId}/price`, { body });
    },

    /**
     * List Inventory
     * GET /products/inventory
     * @param {object} [query]
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.search]
     * @scopes products/prices.readonly
     */
    async getListInventory({ limit, offset, altId, altType, search } = {}) {
      const _params = {};
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (search !== undefined) _params['search'] = search;
      return request('GET', '/products/inventory', { query: _params });
    },

    /**
     * Update Inventory
     * POST /products/inventory
     * @param {object} body — request body
     * @scopes products/prices.write
     */
    async updateInventory(body) {
      return request('POST', '/products/inventory', { body });
    },

    /**
     * Get Price by ID for a Product
     * GET /products/{productId}/price/{priceId}
     * @param {string} productId
     * @param {string} priceId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes products/prices.readonly
     */
    async getPriceByIdForProduct(productId, priceId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/products/${productId}/price/${priceId}`, { query: _params });
    },

    /**
     * Update Price by ID for a Product
     * PUT /products/{productId}/price/{priceId}
     * @param {string} productId
     * @param {string} priceId
     * @param {object} body — request body
     * @scopes products/prices.write
     */
    async updatePriceByIdForProduct(productId, priceId, body) {
      return request('PUT', `/products/${productId}/price/${priceId}`, { body });
    },

    /**
     * Delete Price by ID for a Product
     * DELETE /products/{productId}/price/{priceId}
     * @param {string} productId
     * @param {string} priceId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes products/prices.write
     */
    async deletePriceByIdForProduct(productId, priceId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('DELETE', `/products/${productId}/price/${priceId}`, { query: _params });
    },

    /**
     * Fetch Product Store Stats
     * GET /products/store/{storeId}/stats
     * @param {string} storeId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.search]
     * @param {*} [query.collectionIds]
     * @scopes products.readonly
     */
    async getProductStoreStats(storeId, { altId, altType, search, collectionIds } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (search !== undefined) _params['search'] = search;
      if (collectionIds !== undefined) _params['collectionIds'] = collectionIds;
      return request('GET', `/products/store/${storeId}/stats`, { query: _params });
    },

    /**
     * Action to include/exclude the product in store
     * POST /products/store/{storeId}
     * @param {string} storeId
     * @param {object} body — request body
     * @scopes products.write
     */
    async updateStoreStatus(storeId, body) {
      return request('POST', `/products/store/${storeId}`, { body });
    },

    /**
     * Update product display priorities in store
     * POST /products/store/{storeId}/priority
     * @param {string} storeId
     * @param {object} body — request body
     */
    async updateDisplayPriority(storeId, body) {
      return request('POST', `/products/store/${storeId}/priority`, { body });
    },

    /**
     * Fetch Product Collections
     * GET /products/collections
     * @param {object} [query]
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.collectionIds]
     * @param {*} [query.name]
     * @scopes products/collection.readonly
     */
    async getProductCollection({ limit, offset, altId, altType, collectionIds, name } = {}) {
      const _params = {};
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (collectionIds !== undefined) _params['collectionIds'] = collectionIds;
      if (name !== undefined) _params['name'] = name;
      return request('GET', '/products/collections', { query: _params });
    },

    /**
     * Create Product Collection
     * POST /products/collections
     * @param {object} body — request body
     * @scopes products/collection.write
     */
    async createProductCollection(body) {
      return request('POST', '/products/collections', { body });
    },

    /**
     * Get Details about individual product collection
     * GET /products/collections/{collectionId}
     * @param {string} collectionId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @scopes products/collection.readonly
     */
    async getProductCollectionId(collectionId, { altId } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      return request('GET', `/products/collections/${collectionId}`, { query: _params });
    },

    /**
     * Update Product Collection
     * PUT /products/collections/{collectionId}
     * @param {string} collectionId
     * @param {object} body — request body
     * @scopes products/collection.write
     */
    async updateProductCollection(collectionId, body) {
      return request('PUT', `/products/collections/${collectionId}`, { body });
    },

    /**
     * Delete Product Collection
     * DELETE /products/collections/{collectionId}
     * @param {string} collectionId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @scopes products/collection.write
     */
    async deleteProductCollection(collectionId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('DELETE', `/products/collections/${collectionId}`, { query: _params });
    },

    /**
     * Fetch Product Reviews
     * GET /products/reviews
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.sortField]
     * @param {*} [query.sortOrder]
     * @param {*} [query.rating]
     * @param {*} [query.startDate]
     * @param {*} [query.endDate]
     * @param {*} [query.productId]
     * @param {*} [query.storeId]
     * @scopes products.readonly
     */
    async getProductReviews({ altId, altType, limit, offset, sortField, sortOrder, rating, startDate, endDate, productId, storeId } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (sortField !== undefined) _params['sortField'] = sortField;
      if (sortOrder !== undefined) _params['sortOrder'] = sortOrder;
      if (rating !== undefined) _params['rating'] = rating;
      if (startDate !== undefined) _params['startDate'] = startDate;
      if (endDate !== undefined) _params['endDate'] = endDate;
      if (productId !== undefined) _params['productId'] = productId;
      if (storeId !== undefined) _params['storeId'] = storeId;
      return request('GET', '/products/reviews', { query: _params });
    },

    /**
     * Fetch Review Count as per status
     * GET /products/reviews/count
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.rating]
     * @param {*} [query.startDate]
     * @param {*} [query.endDate]
     * @param {*} [query.productId]
     * @param {*} [query.storeId]
     * @scopes products.readonly
     */
    async getReviewsCount({ altId, altType, rating, startDate, endDate, productId, storeId } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (rating !== undefined) _params['rating'] = rating;
      if (startDate !== undefined) _params['startDate'] = startDate;
      if (endDate !== undefined) _params['endDate'] = endDate;
      if (productId !== undefined) _params['productId'] = productId;
      if (storeId !== undefined) _params['storeId'] = storeId;
      return request('GET', '/products/reviews/count', { query: _params });
    },

    /**
     * Update Product Reviews
     * PUT /products/reviews/{reviewId}
     * @param {string} reviewId
     * @param {object} body — request body
     * @scopes products.write
     */
    async updateProductReview(reviewId, body) {
      return request('PUT', `/products/reviews/${reviewId}`, { body });
    },

    /**
     * Delete Product Review
     * DELETE /products/reviews/{reviewId}
     * @param {string} reviewId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.productId] (required)
     * @scopes products.write
     */
    async deleteProductReview(reviewId, { altId, altType, productId } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (productId !== undefined) _params['productId'] = productId;
      return request('DELETE', `/products/reviews/${reviewId}`, { query: _params });
    },

    /**
     * Update Product Reviews
     * POST /products/reviews/bulk-update
     * @param {object} body — request body
     * @scopes products.write
     */
    async bulkUpdateProductReview(body) {
      return request('POST', '/products/reviews/bulk-update', { body });
    },

    /**
     * Get Product by ID
     * GET /products/{productId}
     * @param {string} productId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.sendWishlistStatus]
     * @scopes products.readonly
     */
    async getProductById(productId, { locationId, sendWishlistStatus } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (sendWishlistStatus !== undefined) _params['sendWishlistStatus'] = sendWishlistStatus;
      return request('GET', `/products/${productId}`, { query: _params });
    },

    /**
     * Update Product by ID
     * PUT /products/{productId}
     * @param {string} productId
     * @param {object} body — request body
     * @scopes products.write
     */
    async updateProductById(productId, body) {
      return request('PUT', `/products/${productId}`, { body });
    },

    /**
     * Delete Product by ID
     * DELETE /products/{productId}
     * @param {string} productId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.sendWishlistStatus]
     * @scopes products.write
     */
    async deleteProductById(productId, { locationId, sendWishlistStatus } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (sendWishlistStatus !== undefined) _params['sendWishlistStatus'] = sendWishlistStatus;
      return request('DELETE', `/products/${productId}`, { query: _params });
    },

    /**
     * List Products
     * GET /products/
     * @param {object} [query]
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.search]
     * @param {*} [query.collectionIds]
     * @param {*} [query.collectionSlug]
     * @param {*} [query.expand]
     * @param {*} [query.productIds]
     * @param {*} [query.storeId]
     * @param {*} [query.includedInStore]
     * @param {*} [query.availableInStore]
     * @param {*} [query.sortOrder]
     * @scopes products.readonly
     */
    async listInvoices({ limit, offset, locationId, search, collectionIds, collectionSlug, expand, productIds, storeId, includedInStore, availableInStore, sortOrder } = {}) {
      const _params = {};
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (search !== undefined) _params['search'] = search;
      if (collectionIds !== undefined) _params['collectionIds'] = collectionIds;
      if (collectionSlug !== undefined) _params['collectionSlug'] = collectionSlug;
      if (expand !== undefined) _params['expand'] = expand;
      if (productIds !== undefined) _params['productIds'] = productIds;
      if (storeId !== undefined) _params['storeId'] = storeId;
      if (includedInStore !== undefined) _params['includedInStore'] = includedInStore;
      if (availableInStore !== undefined) _params['availableInStore'] = availableInStore;
      if (sortOrder !== undefined) _params['sortOrder'] = sortOrder;
      return request('GET', '/products/', { query: _params });
    },

    /**
     * Create Product
     * POST /products/
     * @param {object} body — request body
     * @scopes products.write
     */
    async createProduct(body) {
      return request('POST', '/products/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  bulkUpdate: ["products.write"],
  listPricesForProduct: ["products/prices.readonly"],
  createPriceForProduct: ["products/prices.write"],
  getListInventory: ["products/prices.readonly"],
  updateInventory: ["products/prices.write"],
  getPriceByIdForProduct: ["products/prices.readonly"],
  updatePriceByIdForProduct: ["products/prices.write"],
  deletePriceByIdForProduct: ["products/prices.write"],
  getProductStoreStats: ["products.readonly"],
  updateStoreStatus: ["products.write"],
  getProductCollection: ["products/collection.readonly"],
  createProductCollection: ["products/collection.write"],
  getProductCollectionId: ["products/collection.readonly"],
  updateProductCollection: ["products/collection.write"],
  deleteProductCollection: ["products/collection.write"],
  getProductReviews: ["products.readonly"],
  getReviewsCount: ["products.readonly"],
  updateProductReview: ["products.write"],
  deleteProductReview: ["products.write"],
  bulkUpdateProductReview: ["products.write"],
  getProductById: ["products.readonly"],
  updateProductById: ["products.write"],
  deleteProductById: ["products.write"],
  listInvoices: ["products.readonly"],
  createProduct: ["products.write"],
};
