/**
 * GHL API — proposals namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 4 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the proposals namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all proposals operations
 */
export function createProposalsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * List documents
     * GET /proposals/document
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.status]
     * @param {*} [query.paymentStatus]
     * @param {*} [query.limit]
     * @param {*} [query.skip]
     * @param {*} [query.query]
     * @param {*} [query.dateFrom]
     * @param {*} [query.dateTo]
     */
    async listDocumentsContracts({ locationId, status, paymentStatus, limit, skip, query, dateFrom, dateTo } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (status !== undefined) _params['status'] = status;
      if (paymentStatus !== undefined) _params['paymentStatus'] = paymentStatus;
      if (limit !== undefined) _params['limit'] = limit;
      if (skip !== undefined) _params['skip'] = skip;
      if (query !== undefined) _params['query'] = query;
      if (dateFrom !== undefined) _params['dateFrom'] = dateFrom;
      if (dateTo !== undefined) _params['dateTo'] = dateTo;
      return request('GET', '/proposals/document', { query: _params });
    },

    /**
     * Send document
     * POST /proposals/document/send
     * @param {object} body — request body
     */
    async sendDocumentsContracts(body) {
      return request('POST', '/proposals/document/send', { body });
    },

    /**
     * List templates
     * GET /proposals/templates
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.dateFrom]
     * @param {*} [query.dateTo]
     * @param {*} [query.type]
     * @param {*} [query.name]
     * @param {*} [query.isPublicDocument]
     * @param {*} [query.userId]
     * @param {*} [query.limit]
     * @param {*} [query.skip]
     */
    async listDocumentsContractsTemplates({ locationId, dateFrom, dateTo, type, name, isPublicDocument, userId, limit, skip } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (dateFrom !== undefined) _params['dateFrom'] = dateFrom;
      if (dateTo !== undefined) _params['dateTo'] = dateTo;
      if (type !== undefined) _params['type'] = type;
      if (name !== undefined) _params['name'] = name;
      if (isPublicDocument !== undefined) _params['isPublicDocument'] = isPublicDocument;
      if (userId !== undefined) _params['userId'] = userId;
      if (limit !== undefined) _params['limit'] = limit;
      if (skip !== undefined) _params['skip'] = skip;
      return request('GET', '/proposals/templates', { query: _params });
    },

    /**
     * Send template
     * POST /proposals/templates/send
     * @param {object} body — request body
     */
    async sendDocumentsContractsTemplate(body) {
      return request('POST', '/proposals/templates/send', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
};
