/**
 * GHL API — saas-api namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 22 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the saas-api namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all saas-api operations
 */
export function createSaasApiNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get locations by stripeId with companyId
     * GET /saas-api/public-api/locations
     * @param {object} [query]
     * @param {*} [query.customerId]
     * @param {*} [query.subscriptionId]
     * @param {*} [query.companyId] (required)
     */
    async locationsDeprecated({ customerId, subscriptionId, companyId } = {}) {
      const _params = {};
      if (customerId !== undefined) _params['customerId'] = customerId;
      if (subscriptionId !== undefined) _params['subscriptionId'] = subscriptionId;
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', '/saas-api/public-api/locations', { query: _params });
    },

    /**
     * Update SaaS subscription
     * PUT /saas-api/public-api/update-saas-subscription/{locationId}
     * @param {string} locationId
     * @param {object} body — request body
     */
    async updateSaasSubscriptionDeprecated(locationId, body) {
      return request('PUT', `/saas-api/public-api/update-saas-subscription/${locationId}`, { body });
    },

    /**
     * Disable SaaS for locations
     * POST /saas-api/public-api/bulk-disable-saas/{companyId}
     * @param {string} companyId
     * @param {object} body — request body
     */
    async bulkDisableSaasDeprecated(companyId, body) {
      return request('POST', `/saas-api/public-api/bulk-disable-saas/${companyId}`, { body });
    },

    /**
     * Enable SaaS for Sub-Account (Formerly Location)
     * POST /saas-api/public-api/enable-saas/{locationId}
     * @param {string} locationId
     * @param {object} body — request body
     */
    async enableSaasLocationDeprecated(locationId, body) {
      return request('POST', `/saas-api/public-api/enable-saas/${locationId}`, { body });
    },

    /**
     * Pause location
     * POST /saas-api/public-api/pause/{locationId}
     * @param {string} locationId
     * @param {object} body — request body
     */
    async pauseLocationDeprecated(locationId, body) {
      return request('POST', `/saas-api/public-api/pause/${locationId}`, { body });
    },

    /**
     * Update Rebilling
     * POST /saas-api/public-api/update-rebilling/{companyId}
     * @param {string} companyId
     * @param {object} body — request body
     */
    async updateRebillingDeprecated(companyId, body) {
      return request('POST', `/saas-api/public-api/update-rebilling/${companyId}`, { body });
    },

    /**
     * Get Agency Plans
     * GET /saas-api/public-api/agency-plans/{companyId}
     * @param {string} companyId
     */
    async getAgencyPlansDeprecated(companyId) {
      return request('GET', `/saas-api/public-api/agency-plans/${companyId}`);
    },

    /**
     * Get Location Subscription Details
     * GET /saas-api/public-api/get-saas-subscription/{locationId}
     * @param {string} locationId
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     */
    async getLocationSubscriptionDeprecated(locationId, { companyId } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', `/saas-api/public-api/get-saas-subscription/${locationId}`, { query: _params });
    },

    /**
     * Bulk Enable SaaS
     * POST /saas-api/public-api/bulk-enable-saas/{companyId}
     * @param {string} companyId
     * @param {object} body — request body
     */
    async bulkEnableSaasDeprecated(companyId, body) {
      return request('POST', `/saas-api/public-api/bulk-enable-saas/${companyId}`, { body });
    },

    /**
     * Get SaaS Locations
     * GET /saas-api/public-api/saas-locations/{companyId}
     * @param {string} companyId
     * @param {object} [query]
     * @param {*} [query.page]
     */
    async getSaasLocationsDeprecated(companyId, { page } = {}) {
      const _params = {};
      if (page !== undefined) _params['page'] = page;
      return request('GET', `/saas-api/public-api/saas-locations/${companyId}`, { query: _params });
    },

    /**
     * Get SaaS Plan
     * GET /saas-api/public-api/saas-plan/{planId}
     * @param {string} planId
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     */
    async getSaasPlanDeprecated(planId, { companyId } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', `/saas-api/public-api/saas-plan/${planId}`, { query: _params });
    },

    /**
     * Get locations by stripeId with companyId
     * GET /saas/locations
     * @param {object} [query]
     * @param {*} [query.customerId] (required)
     * @param {*} [query.subscriptionId] (required)
     * @param {*} [query.companyId] (required)
     */
    async locations({ customerId, subscriptionId, companyId } = {}) {
      const _params = {};
      if (customerId !== undefined) _params['customerId'] = customerId;
      if (subscriptionId !== undefined) _params['subscriptionId'] = subscriptionId;
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', '/saas/locations', { query: _params });
    },

    /**
     * Update SaaS subscription
     * PUT /saas/update-saas-subscription/{locationId}
     * @param {string} locationId
     * @param {object} body — request body
     */
    async generatePaymentLink(locationId, body) {
      return request('PUT', `/saas/update-saas-subscription/${locationId}`, { body });
    },

    /**
     * Disable SaaS for locations
     * POST /saas/bulk-disable-saas/{companyId}
     * @param {string} companyId
     * @param {object} body — request body
     */
    async bulkDisableSaas(companyId, body) {
      return request('POST', `/saas/bulk-disable-saas/${companyId}`, { body });
    },

    /**
     * Enable SaaS for Sub-Account (Formerly Location)
     * POST /saas/enable-saas/{locationId}
     * @param {string} locationId
     * @param {object} body — request body
     */
    async enableSaasLocation(locationId, body) {
      return request('POST', `/saas/enable-saas/${locationId}`, { body });
    },

    /**
     * Pause location
     * POST /saas/pause/{locationId}
     * @param {string} locationId
     * @param {object} body — request body
     */
    async pauseLocation(locationId, body) {
      return request('POST', `/saas/pause/${locationId}`, { body });
    },

    /**
     * Update Rebilling
     * POST /saas/update-rebilling/{companyId}
     * @param {string} companyId
     * @param {object} body — request body
     */
    async updateRebilling(companyId, body) {
      return request('POST', `/saas/update-rebilling/${companyId}`, { body });
    },

    /**
     * Get Agency Plans
     * GET /saas/agency-plans/{companyId}
     * @param {string} companyId
     */
    async getAgencyPlans(companyId) {
      return request('GET', `/saas/agency-plans/${companyId}`);
    },

    /**
     * Get Location Subscription Details
     * GET /saas/get-saas-subscription/{locationId}
     * @param {string} locationId
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     */
    async getLocationSubscription(locationId, { companyId } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', `/saas/get-saas-subscription/${locationId}`, { query: _params });
    },

    /**
     * Bulk Enable SaaS
     * POST /saas/bulk-enable-saas/{companyId}
     * @param {string} companyId
     * @param {object} body — request body
     */
    async bulkEnableSaas(companyId, body) {
      return request('POST', `/saas/bulk-enable-saas/${companyId}`, { body });
    },

    /**
     * Get SaaS Locations
     * GET /saas/saas-locations/{companyId}
     * @param {string} companyId
     * @param {object} [query]
     * @param {*} [query.page] (required)
     */
    async getSaasLocations(companyId, { page } = {}) {
      const _params = {};
      if (page !== undefined) _params['page'] = page;
      return request('GET', `/saas/saas-locations/${companyId}`, { query: _params });
    },

    /**
     * Get SaaS Plan
     * GET /saas/saas-plan/{planId}
     * @param {string} planId
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     */
    async getSaasPlan(planId, { companyId } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', `/saas/saas-plan/${planId}`, { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
};
