/**
 * GHL API — snapshots namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 4 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the snapshots namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all snapshots operations
 */
export function createSnapshotsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Snapshots
     * GET /snapshots/
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     */
    async getCustomSnapshots({ companyId } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', '/snapshots/', { query: _params });
    },

    /**
     * Create Snapshot Share Link
     * POST /snapshots/share/link
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     * @param {object} body — request body
     */
    async createSnapshotShareLink({ companyId } = {}, body) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('POST', '/snapshots/share/link', { query: _params, body });
    },

    /**
     * Get Snapshot Push between Dates
     * GET /snapshots/snapshot-status/{snapshotId}
     * @param {string} snapshotId
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     * @param {*} [query.from] (required)
     * @param {*} [query.to] (required)
     * @param {*} [query.lastDoc] (required)
     * @param {*} [query.limit] (required)
     */
    async getSnapshotPush(snapshotId, { companyId, from, to, lastDoc, limit } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      if (from !== undefined) _params['from'] = from;
      if (to !== undefined) _params['to'] = to;
      if (lastDoc !== undefined) _params['lastDoc'] = lastDoc;
      if (limit !== undefined) _params['limit'] = limit;
      return request('GET', `/snapshots/snapshot-status/${snapshotId}`, { query: _params });
    },

    /**
     * Get Last Snapshot Push
     * GET /snapshots/snapshot-status/{snapshotId}/location/{locationId}
     * @param {string} snapshotId
     * @param {string} locationId
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     */
    async getLatestSnapshotPush(snapshotId, locationId, { companyId } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      return request('GET', `/snapshots/snapshot-status/${snapshotId}/location/${locationId}`, { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
};
