/**
 * GHL API — store namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 18 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the store namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all store operations
 */
export function createStoreNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * List Shipping Zones
     * GET /store/shipping-zone
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     * @param {*} [query.withShippingRate]
     */
    async listShippingZones({ altId, altType, limit, offset, withShippingRate } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      if (withShippingRate !== undefined) _params['withShippingRate'] = withShippingRate;
      return request('GET', '/store/shipping-zone', { query: _params });
    },

    /**
     * Create Shipping Zone
     * POST /store/shipping-zone
     * @param {object} body — request body
     */
    async createShippingZone(body) {
      return request('POST', '/store/shipping-zone', { body });
    },

    /**
     * Get Shipping Zone
     * GET /store/shipping-zone/{shippingZoneId}
     * @param {string} shippingZoneId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.withShippingRate]
     */
    async getShippingZones(shippingZoneId, { altId, altType, withShippingRate } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (withShippingRate !== undefined) _params['withShippingRate'] = withShippingRate;
      return request('GET', `/store/shipping-zone/${shippingZoneId}`, { query: _params });
    },

    /**
     * Update Shipping Zone
     * PUT /store/shipping-zone/{shippingZoneId}
     * @param {string} shippingZoneId
     * @param {object} body — request body
     */
    async updateShippingZone(shippingZoneId, body) {
      return request('PUT', `/store/shipping-zone/${shippingZoneId}`, { body });
    },

    /**
     * Delete shipping zone
     * DELETE /store/shipping-zone/{shippingZoneId}
     * @param {string} shippingZoneId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async deleteShippingZone(shippingZoneId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('DELETE', `/store/shipping-zone/${shippingZoneId}`, { query: _params });
    },

    /**
     * Get available shipping rates
     * POST /store/shipping-zone/shipping-rates
     * @param {object} body — request body
     */
    async getAvailableShippingZones(body) {
      return request('POST', '/store/shipping-zone/shipping-rates', { body });
    },

    /**
     * List Shipping Rates
     * GET /store/shipping-zone/{shippingZoneId}/shipping-rate
     * @param {string} shippingZoneId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     * @param {*} [query.limit]
     * @param {*} [query.offset]
     */
    async listShippingRates(shippingZoneId, { altId, altType, limit, offset } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      if (limit !== undefined) _params['limit'] = limit;
      if (offset !== undefined) _params['offset'] = offset;
      return request('GET', `/store/shipping-zone/${shippingZoneId}/shipping-rate`, { query: _params });
    },

    /**
     * Create Shipping Rate
     * POST /store/shipping-zone/{shippingZoneId}/shipping-rate
     * @param {string} shippingZoneId
     * @param {object} body — request body
     */
    async createShippingRate(shippingZoneId, body) {
      return request('POST', `/store/shipping-zone/${shippingZoneId}/shipping-rate`, { body });
    },

    /**
     * Get Shipping Rate
     * GET /store/shipping-zone/{shippingZoneId}/shipping-rate/{shippingRateId}
     * @param {string} shippingZoneId
     * @param {string} shippingRateId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async getShippingRates(shippingZoneId, shippingRateId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/store/shipping-zone/${shippingZoneId}/shipping-rate/${shippingRateId}`, { query: _params });
    },

    /**
     * Update Shipping Rate
     * PUT /store/shipping-zone/{shippingZoneId}/shipping-rate/{shippingRateId}
     * @param {string} shippingZoneId
     * @param {string} shippingRateId
     * @param {object} body — request body
     */
    async updateShippingRate(shippingZoneId, shippingRateId, body) {
      return request('PUT', `/store/shipping-zone/${shippingZoneId}/shipping-rate/${shippingRateId}`, { body });
    },

    /**
     * Delete shipping rate
     * DELETE /store/shipping-zone/{shippingZoneId}/shipping-rate/{shippingRateId}
     * @param {string} shippingZoneId
     * @param {string} shippingRateId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async deleteShippingRate(shippingZoneId, shippingRateId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('DELETE', `/store/shipping-zone/${shippingZoneId}/shipping-rate/${shippingRateId}`, { query: _params });
    },

    /**
     * List Shipping Carriers
     * GET /store/shipping-carrier
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async listShippingCarriers({ altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', '/store/shipping-carrier', { query: _params });
    },

    /**
     * Create Shipping Carrier
     * POST /store/shipping-carrier
     * @param {object} body — request body
     */
    async createShippingCarrier(body) {
      return request('POST', '/store/shipping-carrier', { body });
    },

    /**
     * Get Shipping Carrier
     * GET /store/shipping-carrier/{shippingCarrierId}
     * @param {string} shippingCarrierId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async getShippingCarriers(shippingCarrierId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', `/store/shipping-carrier/${shippingCarrierId}`, { query: _params });
    },

    /**
     * Update Shipping Carrier
     * PUT /store/shipping-carrier/{shippingCarrierId}
     * @param {string} shippingCarrierId
     * @param {object} body — request body
     */
    async updateShippingCarrier(shippingCarrierId, body) {
      return request('PUT', `/store/shipping-carrier/${shippingCarrierId}`, { body });
    },

    /**
     * Delete shipping carrier
     * DELETE /store/shipping-carrier/{shippingCarrierId}
     * @param {string} shippingCarrierId
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async deleteShippingCarrier(shippingCarrierId, { altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('DELETE', `/store/shipping-carrier/${shippingCarrierId}`, { query: _params });
    },

    /**
     * Get Store Settings
     * GET /store/store-setting
     * @param {object} [query]
     * @param {*} [query.altId] (required)
     * @param {*} [query.altType] (required)
     */
    async getStoreSettings({ altId, altType } = {}) {
      const _params = {};
      if (altId !== undefined) _params['altId'] = altId;
      if (altType !== undefined) _params['altType'] = altType;
      return request('GET', '/store/store-setting', { query: _params });
    },

    /**
     * Create/Update Store Settings
     * POST /store/store-setting
     * @param {object} body — request body
     */
    async createStoreSetting(body) {
      return request('POST', '/store/store-setting', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
};
