/**
 * GHL API — surveys namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 2 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the surveys namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all surveys operations
 */
export function createSurveysNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Surveys Submissions
     * GET /surveys/submissions
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.page]
     * @param {*} [query.limit]
     * @param {*} [query.surveyId]
     * @param {*} [query.q]
     * @param {*} [query.startAt]
     * @param {*} [query.endAt]
     * @scopes surveys.readonly
     */
    async getSurveysSubmissions({ locationId, page, limit, surveyId, q, startAt, endAt } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (page !== undefined) _params['page'] = page;
      if (limit !== undefined) _params['limit'] = limit;
      if (surveyId !== undefined) _params['surveyId'] = surveyId;
      if (q !== undefined) _params['q'] = q;
      if (startAt !== undefined) _params['startAt'] = startAt;
      if (endAt !== undefined) _params['endAt'] = endAt;
      return request('GET', '/surveys/submissions', { query: _params });
    },

    /**
     * Get Surveys
     * GET /surveys/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @param {*} [query.type]
     * @scopes surveys.readonly
     */
    async getSurveys({ locationId, skip, limit, type } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (type !== undefined) _params['type'] = type;
      return request('GET', '/surveys/', { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getSurveysSubmissions: ["surveys.readonly"],
  getSurveys: ["surveys.readonly"],
};
