/**
 * GHL API — users namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 7 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the users namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all users operations
 */
export function createUsersNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Search Users
     * GET /users/search
     * @param {object} [query]
     * @param {*} [query.companyId] (required)
     * @param {*} [query.query]
     * @param {*} [query.skip]
     * @param {*} [query.limit]
     * @param {*} [query.locationId]
     * @param {*} [query.type]
     * @param {*} [query.role]
     * @param {*} [query.ids]
     * @param {*} [query.sort]
     * @param {*} [query.sortDirection]
     * @param {*} [query.enabled2waySync]
     * @scopes users.readonly
     */
    async searchUsers({ companyId, query, skip, limit, locationId, type, role, ids, sort, sortDirection, enabled2waySync } = {}) {
      const _params = {};
      if (companyId !== undefined) _params['companyId'] = companyId;
      if (query !== undefined) _params['query'] = query;
      if (skip !== undefined) _params['skip'] = skip;
      if (limit !== undefined) _params['limit'] = limit;
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (type !== undefined) _params['type'] = type;
      if (role !== undefined) _params['role'] = role;
      if (ids !== undefined) _params['ids'] = ids;
      if (sort !== undefined) _params['sort'] = sort;
      if (sortDirection !== undefined) _params['sortDirection'] = sortDirection;
      if (enabled2waySync !== undefined) _params['enabled2waySync'] = enabled2waySync;
      return request('GET', '/users/search', { query: _params });
    },

    /**
     * Filter Users by Email
     * POST /users/search/filter-by-email
     * @param {object} body — request body
     * @scopes users.readonly
     */
    async filterUsersByEmail(body) {
      return request('POST', '/users/search/filter-by-email', { body });
    },

    /**
     * Get User
     * GET /users/{userId}
     * @param {string} userId
     * @scopes users.readonly
     */
    async getUser(userId) {
      return request('GET', `/users/${userId}`);
    },

    /**
     * Update User
     * PUT /users/{userId}
     * @param {string} userId
     * @param {object} body — request body
     * @scopes users.write
     */
    async updateUser(userId, body) {
      return request('PUT', `/users/${userId}`, { body });
    },

    /**
     * Delete User
     * DELETE /users/{userId}
     * @param {string} userId
     * @scopes users.write
     */
    async deleteUser(userId) {
      return request('DELETE', `/users/${userId}`);
    },

    /**
     * Get User by Location
     * GET /users/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes users.readonly
     */
    async getUserByLocation({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/users/', { query: _params });
    },

    /**
     * Create User
     * POST /users/
     * @param {object} body — request body
     * @scopes users.write
     */
    async createUser(body) {
      return request('POST', '/users/', { body });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  searchUsers: ["users.readonly"],
  filterUsersByEmail: ["users.readonly"],
  getUser: ["users.readonly"],
  updateUser: ["users.write"],
  deleteUser: ["users.write"],
  getUserByLocation: ["users.readonly"],
  createUser: ["users.write"],
};
