/**
 * GHL API — voice-ai namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 11 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the voice-ai namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all voice-ai operations
 */
export function createVoiceAiNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * List Agents
     * GET /voice-ai/agents
     * @param {object} [query]
     * @param {*} [query.page]
     * @param {*} [query.pageSize]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.query]
     * @scopes voice-ai-agents.readonly
     */
    async getAgents({ page, pageSize, locationId, query } = {}) {
      const _params = {};
      if (page !== undefined) _params['page'] = page;
      if (pageSize !== undefined) _params['pageSize'] = pageSize;
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (query !== undefined) _params['query'] = query;
      return request('GET', '/voice-ai/agents', { query: _params });
    },

    /**
     * Create Agent
     * POST /voice-ai/agents
     * @param {object} body — request body
     * @scopes voice-ai-agents.write
     */
    async createAgent(body) {
      return request('POST', '/voice-ai/agents', { body });
    },

    /**
     * Get Agent
     * GET /voice-ai/agents/{agentId}
     * @param {string} agentId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes voice-ai-agents.readonly
     */
    async getAgent(agentId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/voice-ai/agents/${agentId}`, { query: _params });
    },

    /**
     * Patch Agent
     * PATCH /voice-ai/agents/{agentId}
     * @param {string} agentId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {object} body — request body
     * @scopes voice-ai-agents.write
     */
    async patchAgent(agentId, { locationId } = {}, body) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('PATCH', `/voice-ai/agents/${agentId}`, { query: _params, body });
    },

    /**
     * Delete Agent
     * DELETE /voice-ai/agents/{agentId}
     * @param {string} agentId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes voice-ai-agents.write
     */
    async deleteAgent(agentId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('DELETE', `/voice-ai/agents/${agentId}`, { query: _params });
    },

    /**
     * List Call Logs
     * GET /voice-ai/dashboard/call-logs
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.agentId]
     * @param {*} [query.contactId]
     * @param {*} [query.callType]
     * @param {*} [query.startDate]
     * @param {*} [query.endDate]
     * @param {*} [query.actionType]
     * @param {*} [query.sortBy]
     * @param {*} [query.sort]
     * @param {*} [query.page]
     * @param {*} [query.pageSize]
     * @scopes voice-ai-dashboard.readonly
     */
    async getCallLogs({ locationId, agentId, contactId, callType, startDate, endDate, actionType, sortBy, sort, page, pageSize } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (agentId !== undefined) _params['agentId'] = agentId;
      if (contactId !== undefined) _params['contactId'] = contactId;
      if (callType !== undefined) _params['callType'] = callType;
      if (startDate !== undefined) _params['startDate'] = startDate;
      if (endDate !== undefined) _params['endDate'] = endDate;
      if (actionType !== undefined) _params['actionType'] = actionType;
      if (sortBy !== undefined) _params['sortBy'] = sortBy;
      if (sort !== undefined) _params['sort'] = sort;
      if (page !== undefined) _params['page'] = page;
      if (pageSize !== undefined) _params['pageSize'] = pageSize;
      return request('GET', '/voice-ai/dashboard/call-logs', { query: _params });
    },

    /**
     * Get Call Log
     * GET /voice-ai/dashboard/call-logs/{callId}
     * @param {string} callId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes voice-ai-dashboard.readonly
     */
    async getCallLog(callId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/voice-ai/dashboard/call-logs/${callId}`, { query: _params });
    },

    /**
     * Create Agent Action
     * POST /voice-ai/actions
     * @param {object} body — request body
     * @scopes voice-ai-agent-goals.write
     */
    async createAction(body) {
      return request('POST', '/voice-ai/actions', { body });
    },

    /**
     * Get Agent Action
     * GET /voice-ai/actions/{actionId}
     * @param {string} actionId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes voice-ai-agent-goals.readonly
     */
    async getAction(actionId, { locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', `/voice-ai/actions/${actionId}`, { query: _params });
    },

    /**
     * Update Agent Action
     * PUT /voice-ai/actions/{actionId}
     * @param {string} actionId
     * @param {object} body — request body
     * @scopes voice-ai-agent-goals.write
     */
    async updateAction(actionId, body) {
      return request('PUT', `/voice-ai/actions/${actionId}`, { body });
    },

    /**
     * Delete Agent Action
     * DELETE /voice-ai/actions/{actionId}
     * @param {string} actionId
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @param {*} [query.agentId] (required)
     * @scopes voice-ai-agent-goals.write
     */
    async deleteAction(actionId, { locationId, agentId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      if (agentId !== undefined) _params['agentId'] = agentId;
      return request('DELETE', `/voice-ai/actions/${actionId}`, { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getAgents: ["voice-ai-agents.readonly"],
  createAgent: ["voice-ai-agents.write"],
  getAgent: ["voice-ai-agents.readonly"],
  patchAgent: ["voice-ai-agents.write"],
  deleteAgent: ["voice-ai-agents.write"],
  getCallLogs: ["voice-ai-dashboard.readonly"],
  getCallLog: ["voice-ai-dashboard.readonly"],
  createAction: ["voice-ai-agent-goals.write"],
  getAction: ["voice-ai-agent-goals.readonly"],
  updateAction: ["voice-ai-agent-goals.write"],
  deleteAction: ["voice-ai-agent-goals.write"],
};
