/**
 * GHL API — workflows namespace
 * Auto-generated by scripts/ghl-codegen/generate-client.mjs
 * DO NOT EDIT MANUALLY — regenerate from OpenAPI specs instead.
 *
 * 1 operations
 */

/** @typedef {import('../ghl-tenant-resolver.mjs')} TenantResolver */

/**
 * Create the workflows namespace bound to a resolved tenant context.
 * @param {{ request: Function }} ctx — { request } from the client core
 * @returns {object} namespace with all workflows operations
 */
export function createWorkflowsNamespace(ctx) {
  const { request } = ctx;
  return {
    /**
     * Get Workflow
     * GET /workflows/
     * @param {object} [query]
     * @param {*} [query.locationId] (required)
     * @scopes workflows.readonly
     */
    async getWorkflow({ locationId } = {}) {
      const _params = {};
      if (locationId !== undefined) _params['locationId'] = locationId;
      return request('GET', '/workflows/', { query: _params });
    }
  };
}

/** Scope requirements for each operation in this namespace. */
export const SCOPES = {
  getWorkflow: ["workflows.readonly"],
};
